(function (lib, img, cjs, ss) {

var p; // shortcut to reference prototypes

// library properties:
lib.properties = {
	width: 300,
	height: 600,
	fps: 24,
	color: "#FFFFFF",
	manifest: [
		{src:"images/apple.png", id:"apple"},
		{src:"images/arrow2.png", id:"arrow2"},
		{src:"images/arrow3.png", id:"arrow3"},
		{src:"images/bgImg.jpg", id:"bgImg"},
		{src:"images/billet1.png", id:"billet1"},
		{src:"images/img1.png", id:"img1"},
		{src:"images/line.png", id:"line"},
		{src:"images/orange.png", id:"orange"},
		{src:"images/s1.png", id:"s1"},
		{src:"images/s2.png", id:"s2"},
		{src:"images/s3.png", id:"s3"},
		{src:"images/s4.png", id:"s4"},
		{src:"images/s5.png", id:"s5"},
		{src:"images/vapor.png", id:"vapor"}
	]
};



// symbols:



(lib.apple = function() {
	this.initialize(img.apple);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,48,77);


(lib.arrow2 = function() {
	this.initialize(img.arrow2);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,27,96);


(lib.arrow3 = function() {
	this.initialize(img.arrow3);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,37,82);


(lib.bgImg = function() {
	this.initialize(img.bgImg);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,300,600);


(lib.billet1 = function() {
	this.initialize(img.billet1);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,222,303);


(lib.img1 = function() {
	this.initialize(img.img1);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,300,473);


(lib.line = function() {
	this.initialize(img.line);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,114,12);


(lib.orange = function() {
	this.initialize(img.orange);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,57,66);


(lib.s1 = function() {
	this.initialize(img.s1);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,48,49);


(lib.s2 = function() {
	this.initialize(img.s2);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,39,31);


(lib.s3 = function() {
	this.initialize(img.s3);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,28,26);


(lib.s4 = function() {
	this.initialize(img.s4);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,17,22);


(lib.s5 = function() {
	this.initialize(img.s5);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,20,28);


(lib.vapor = function() {
	this.initialize(img.vapor);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,123,200);


(lib.я = function() {
	this.initialize();

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#0A502F").s().p("AAtCCQgJAAgEgFQgGgGABgKIAAhzIgqBzQgDAIgHAHQgHAFgJAAIgqAAIAuhwQgbgLgGglQgCgdADgbQAHgqAuAAIBSABQAIgBAFAGQAGAGgBAJIgBDugAgNhBQgBAMACASQACAcASAAIATAAIAAhSIgSAAQgTgBgDAZg");

	this.addChild(this.shape);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(-8.5,-13,17,26.1);


(lib.ш1 = function() {
	this.initialize();

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#C00000").s().p("AhqCBQgJAAgEgGQgGgGAAgJIABjtIAmAAQAIAAAGAGQAEAFAAAKIAADGIApAAIABjbIAjAAIADABIADAAIABAAIADACQAEACADAGIABADIABAFIgBDIIAqAAIAAjbIAmAAQAIAAAFAGQAFAFAAAKIAADug");

	this.addChild(this.shape);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(-12.6,-13,25.2,26.1);


(lib.ч = function() {
	this.initialize();

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#0A502F").s().p("AApCCQgIAAgFgFQgFgGAAgKIAAhVIghABQgXgBgMgFQgOgGgJgLQgMgNABgUIAAhiIAmAAQAIAAAFAGQAFAGAAAKIAABIQAAAcAXAAIAXAAIABh5IAmAAQAIAAAFAFQAFAHAAAJIAADtg");

	this.addChild(this.shape);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(-8,-13,16.2,26.1);


(lib.у1 = function() {
	this.initialize();

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#C00000").s().p("AgiCCQgIAAgGgGQgGgFABgKIAAgSQAPACAHgIQAHgIgEgMIg1jCIAlAAQANAAAGAFQAHAGADANIASB4IAVh5QAFgWAWAAIAfAAIg3DCQgJAggKANQgLATgXAAg");

	this.addChild(this.shape);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(-8.3,-13,16.6,26.1);


(lib.т = function() {
	this.initialize();

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#0A502F").s().p("AgICCQgJAAgFgGQgFgFAAgKIAAjBIgdAAQgNAAgHgJQgHgIAAgNIAAgPICnABIgBAOQAAANgGAJQgIAJgMAAIgegBIAADWg");

	this.addChild(this.shape);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(-8.4,-13,16.9,26.1);


(lib.с1 = function() {
	this.initialize();

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#C00000").s().p("Ag+BpQgLgXAAhUQABhFAKgYQAPgmAyAAQBGAAAAA1IABAwQgIACgLAAQgRAAgJgGQgJgGAAgQQAAgVgCgGQgDgJgMAAQgGAAgEAHQgDAFgCAMQgDAaAAAsQAAA7ACANQACANAEAFQADAFAGAAQAKAAAEgKQAEgLAAgdQAAgQAKgGQAIgGARAAQALAAAIACIAAA8QgCA3hDAAQg1gBgOgcg");

	this.addChild(this.shape);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(-7.4,-13.4,14.9,26.9);


(lib.р1 = function() {
	this.initialize();

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#C00000").s().p("Ag6CCQgIAAgFgGQgGgFAAgKIABjuIBkAAQAuAAAGArQADAagCAdQgGAngdALQgDACgKACQgNADgkAAIAABogAgUgHIATAAQAIAAAGgIQAGgIAAgMQACgSgBgMQgBgZgUAAIgTAAg");

	this.addChild(this.shape);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(-7.8,-13,15.7,26.1);


(lib.р = function() {
	this.initialize();

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#0A502F").s().p("Ag6CCQgJAAgFgGQgFgFAAgKIABjuIBkAAQAvABAFAqQADAagCAdQgDAVgKAMQgJANgNAEQgDADgKABQgQAEghAAIgBBngAgUgHIATAAQAHAAAHgIQAGgIAAgMQACgRgBgNQgBgYgUAAIgTAAg");

	this.addChild(this.shape);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(-7.8,-13,15.7,26.1);


(lib.п1 = function() {
	this.initialize();

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#C00000").s().p("AAqCCQgIAAgGgGQgFgFAAgKIABjGIgvAAIAADbIgmAAQgJAAgEgGQgGgFAAgKIABjuICNAAQAIAAAFAGQAFAGAAAKIAADtg");

	this.addChild(this.shape);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(-8.1,-13,16.2,26.1);


(lib.о1 = function() {
	this.initialize();

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#C00000").s().p("AgzB6QgTgNgEgiQgCgUAAg0QgBg1ADgVQAFgiAWgQQASgLAfgBQAmABARAQQAPAOADAdQADAaAAAvQAAA0gEAXQgEAegRANQgSAPghABQgkAAgRgMgAgRhGQgCASgBA1QAAA4ACAPQAEAYAOAAQARAAACgZQABgRABg1QAAg3gBgQQgBgKgDgGQgEgIgLAAQgOAAgEAYg");

	this.addChild(this.shape);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(-7.8,-13.4,15.6,26.8);


(lib.о = function() {
	this.initialize();

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#0A502F").s().p("AgzB6QgUgNgDghQgCgXgBgyQAAg2ADgUQAFgjAWgPQASgMAfAAQAmABARAQQAPAOADAdQADAagBAvQAAA0gEAYQgEAdgRAOQgRAOgiABQgjAAgRgMgAgRhGQgDATAAA0QAAA4ACAQQADAWAPAAQAIABAFgGQAEgFACgOQABgSABg0QAAg3gCgQQgBgLgCgEQgEgJgLAAQgOAAgEAYg");

	this.addChild(this.shape);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(-7.8,-13.4,15.6,26.9);


(lib.н1 = function() {
	this.initialize();

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#C00000").s().p("AAqCCQgIAAgGgGQgEgFAAgKIAAhjIgvAAIAAB4IgmAAQgIAAgFgGQgFgFgBgKIABjuIAmAAQAIAAAGAGQAFAGgBAKIAABPIAvAAIAAhlIAmAAQAJAAAEAGQAGAGgBAKIAADtg");

	this.addChild(this.shape);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(-8.1,-13,16.2,26.1);


(lib.н = function() {
	this.initialize();

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#0A502F").s().p("AAqCBQgIABgGgGQgEgGAAgJIAAhkIgvAAIAAB4IgmAAQgJABgEgGQgGgFAAgLIABjtIAmAAQAIAAAGAGQAFAGgBAKIAABPIAvAAIAAhlIAmABQAJAAAEAFQAGAHgBAJIAADtg");

	this.addChild(this.shape);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(-8.1,-13,16.2,26.1);


(lib.и1 = function() {
	this.initialize();

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#C00000").s().p("AAzCCQgIAAgFgFQgFgGAAgKIAAiaIg2CuIgwAAQgIABgFgGQgGgGABgJIAAjuIAlAAQAIAAAFAFQAFAGAAAKIAACZIAviYQACgKAHgGQAHgFALAAIAvAAIgBECg");

	this.addChild(this.shape);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(-8.9,-13,17.8,26.1);


(lib.и = function() {
	this.initialize();

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#0A502F").s().p("AAzCBQgIABgFgGQgGgGABgJIAAiaIg2CuIgwAAQgJABgEgGQgGgFAAgLIABjtIAlAAQAIAAAFAFQAGAGgBAKIAACZIAviZQACgJAHgGQAHgGALABIAvAAIgBECg");

	this.addChild(this.shape);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(-8.9,-13,17.8,26.1);


(lib.е = function() {
	this.initialize();

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#0A502F").s().p("Ag+CCIABkDIB7ABIAAAJQAAAMgHAIQgIAKgNAAIgmAAIgBA9IA3AAIAAAJQgBAMgHAHQgIAKgOAAIgZAAIAABQIBDAAIAAAIQABAPgJAIQgIAJgPAAg");

	this.addChild(this.shape);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(-6.3,-13,12.6,26.1);


(lib.д1 = function() {
	this.initialize();

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#C00000").s().p("ABNCXQgJAAgFgFQgFgGAAgJIAAgXIhzAAIAAAXQgBAUgSAAIgcAAIAAhSIAQAAQARgDAAgTIABjFICAAAQAIAAAFAGQAGAGAAAKIgBDFIAKAAQAIAAAFAGQAGAGAAAKIgBA8gAgYAzQABAKgCAIIAsAAIABi0IgrAAg");

	this.addChild(this.shape);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(-10.5,-15.1,21,30.4);


(lib.д = function() {
	this.initialize();

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#0A502F").s().p("ABNCXQgJAAgFgGQgFgFAAgJIAAgXIhzAAIAAAWQAAAKgGAFQgFAGgIAAIgbAAIAAhTIAQABQARgEAAgSIAAjGICAABQAJAAAFAGQAFAGAAAKIgBDFIAKAAQAIAAAFAFQAFAGAAAKIAAA+gAgXAzQAAAKgCAIIAtAAIAAizIgrgBg");

	this.addChild(this.shape);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(-10.4,-15.2,21,30.4);


(lib.г = function() {
	this.initialize();

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#0A502F").s().p("AgrCBQgIABgFgGQgFgGAAgJIAAjuIB7ABIAAAJQAAAMgHAJQgIAKgNgBIgmAAIgBDbg");

	this.addChild(this.shape);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(-6.3,-13,12.6,26.1);


(lib.в1 = function() {
	this.initialize();

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#C00000").s().p("AhNCCIAAkDIBgAAQAwAAAFAsQACASgCARQgCAOgFAIQgGAKgMAFQAcAIACAjQACAcgEAYQgEAXgRAMQgQANgdAAgAgUBbIAPAAQAJAAAGgFQAFgFACgMQADgTgCgUQgCgUgSAAIgSAAgAgUgcIAPAAQAJAAAFgEQAGgFACgNQABgHgCgOQgCgSgRAAIgRAAg");

	this.addChild(this.shape);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(-7.8,-13,15.7,26.1);


(lib.в = function() {
	this.initialize();

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#0A502F").s().p("AhNCCIABkDIBfAAQAxABAEArQADATgDAQQgCAPgFAIQgGAJgMAGQAcAHACAjQACAbgEAZQgIAwg6AAgAgUBbIAPAAQAKAAAFgFQAGgFACgMQACgYgCgPQgCgUgSAAIgSAAgAgUgcIAPAAQAJABAGgFQAGgFABgNQABgJgBgMQgCgSgRAAIgSAAg");

	this.addChild(this.shape);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(-7.8,-13,15.7,26.1);


(lib.а = function() {
	this.initialize();

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#0A502F").s().p("AA6CCQgKAAgIgGQgHgGgBgJIgMg8IgqAAIgNA7QgCAKgHAGQgHAFgLAAIgeAAIA3kCIAtABQARAAAIAGQAJAHAEASQAEAKAWBuIAVBrgAANAJIgNhRIgOBRIAbAAg");

	this.addChild(this.shape);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(-9.3,-13,18.7,26.1);


(lib.vaporMc = function() {
	this.initialize();

	// Слой 2
	this.instance = new lib.vapor();
	this.instance.setTransform(-61.5,-100);

	// Слой 1
	this.instance_1 = new lib.vapor();
	this.instance_1.setTransform(-61.5,-100);

	this.addChild(this.instance_1,this.instance);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(-61.5,-100,123,200);


(lib.t6 = function() {
	this.initialize();

	// <Слой>
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("ADpF+QgHgHAAgJQAAgKAHgGQAHgHAJAAQAKAAAGAHQAHAGAAAKQAAAJgHAHQgGAGgKAAQgJAAgHgGgAC3GCQgMAAAAgPIAAhgIgbBvIgMAAQgRAAgGgWIgXhZIAABvIgUAAQgNAAAAgPIAAiuIAfAAQAMAAAGAFQAGAFAEANIAVBUIAKgnQALgnABgHQAGgWAVAAIAdAAIAAC9gAAIGCQgMAAAAgPIAAhxIgoCAIgjAAQgNAAAAgPIAAiuIAaAAQAOAAAAAPIAABxIAjhxQADgPAOAAIAiAAIAAC9gAiKGCQgOAAAAgPIAAg+IgZABQgRgBgJgDQgKgEgGgIQgJgLAAgPIAAhHIAcAAQAGAAAEAEQADAFAAAHIAAA1QAAATATAAIAQAAIAAhYIAcAAQAGAAAEAEQADAFAAAHIAACtgAkMGCQgOAAAAgPIAAhVIgOAoIgRAtQgCAHgFAEQgFAEgHAAIgfAAIAihRQgUgJgEgcQgCgWADgSQAEgfAiAAIA8AAQAOAAAAAPIAACugAk4D0IABAVQACAUAOAAIANAAIAAg8IgNAAQgQAAgBATgAnUGCQgGAAgEgEQgEgEAAgHIAAiuIBLAAQAhAAAFAfQADAVgDATQgEAfgVAHIgJADQgSACgUAAIAABLgAm4EeIAOAAQAOAAACgVQABgPgBgHQgBgRgQAAIgNAAgAoFGCQgIAAgFgEQgFgFgBgGIgJgrIggAAIgJArQgEAPgQAAIgVAAIAni9IAiAAQAMAAAGAFQAGAFAEANIAiCmgAomEqIgKg8IgLA8IAVAAgAq2GCQgNAAAAgPIAAiuIBbAAIAAAHQAAAIgGAHQgGAHgJAAIgdAAIgBCggAD1FLQgNAAgBgPIgDh3IAfAAQAGAAADAEQAEAEAAAGIgFB4gAgyBjQgIgRAAg/QAAgwAHgSQAMgbAmAAQAwAAABAmIAAAkIgNAAQgaAAAAgTQAAgPgBgFQgDgHgGAAQgLAAgCASQgCAQAAAiQAAArACAKQABAJADAEQADADAFAAQAGAAADgHQACgIAAgVQAAgUAaAAIAOABIgBAsQAAAogwAAQgoAAgKgVgAJjBjQgIgRAAg+QAAgvAHgRQALgbAlAAQAyAAABAlIAAAUIgNABQgMAAgGgDQgHgFAAgLQgCgMgJAAQgLAAgDASIgCAbIAnAAIAAAHQAAAIgGAHQgGAHgJAAIgSAAQAAAkABAJQACAJADAEQADADAFAAQAHAAADgEQADgFAAgMQAAgUAZAAQAIAAAGACIgBAcQAAAngxAAQgnAAgKgUgAIDB0QgGAAgEgEQgFgEAAgHIAAgNQALABAFgGQAFgFgCgJIgniMIAbAAQAJAAAEAEQAFADACAKIAQBXIAOhXQAFgRAPAAIAXAAIgoCNQgHAXgHAKQgJANgRAAgAHGB0QgGAAgFgEQgFgFgBgGIgchTIAABiIgcAAQgGAAgEgEQgEgEAAgHIAAisIAcAAQAOAAAAAPIAABJIAbhKQADgOANAAIAcAAIgOAkIgUAwIAmBngAFMB0QgIAAgFgEQgFgFgBgGIgJgrIggAAIgJArQgEAPgQAAIgVAAIAni7IAiAAQAMAAAGAFQAGAFAEANIAiCkgAErAcIgKg6IgLA6IAVAAgAC/B0QgMAAAAgPIAAhgIgcBvIgLAAQgRAAgGgWIgXhZIAABvIgUAAQgGAAgEgEQgEgEAAgHIAAisIAgAAQAMAAAGAFQAGAFAEANIAVBSIAWhTQAGgWAVAAIAdAAIAAC7gAkvB0QgGAAgEgEQgDgFAAgHIAAirIAbAAQAOAAAAAPIAACPIAdAAIAAieIAcAAQANAAAAAPIAACPIAeAAIAAieIAbAAQAOAAAAAPIAACsgAlrB0QgGAAgDgEQgEgEAAgHIAAhIIgjAAIAABXIgcAAQgNAAAAgPIAAisIAcAAQAGAAADAEQAEAEAAAHIAAA5IAjAAIAAhIIAcAAQANAAAAAPIAACsgAojB0QgGAAgEgEQgEgEAAgHIAAgNQALABAFgGQAFgFgCgJIgniMIAbAAQAQAAAEARIAPBXIAPhXQAEgRAQAAIAXAAIgoCNQgHAXgHAKQgJANgRAAgApqB0QgGAAgEgEQgEgEAAgHIAAiPIgiAAIAACeIgcAAQgNAAAAgPIAAisIBnAAQAGAAAEAEQAEAFAAAHIAACrgAksh5QgNAAAAgPIAAgQIhVAAIAAAQQAAAHgEAEQgDAEgGAAIgUAAIAAg8IALAAQAMgCAAgNIAAiRIBfAAQAFAAAEAEQAEAFAAAHIAACQIAHAAQAGAAAEAFQADAEAAAHIAAAsgAl2jBIgBAMIAiAAIAAiDIghAAgAhYiUQgbAAgMgJQgPgJgCgZQgCgQAAglQAAgnACgQQADgZARgLQANgJAYAAQAcAAANAMQALAKACAVIACA3QAAAlgCASQgEAWgMAKQgNAKgZABgAhmkqQgCAOAAAnQgBApACALQADARALAAQANAAACgSIABgzQABgpgCgMIgCgLQgEgHgIAAQgLAAgDASgAq8irQgJgSAAhFQAAg3AIgTQANgfApAAQA3AAACArIAAAmQgGABgJAAQgcAAAAgWQAAgQgCgFQgCgIgKAAQgLAAgCAUQgDARAAAoQAAAvACAKQACALADAEQADAEAGAAQAIAAADgIQADgJAAgXQAAgNAIgFQAGgEAOAAQAJAAAGABIAAAwQgBAsg2AAQgsAAgLgXgAFriYQgNAAAAgPIAAhxIgoCAIgkAAQgNAAAAgPIAAiuIAbAAQANAAAAAPIAABxIAjhxQAEgPAQAAIAiAAIAAC9gADYiYQgGAAgDgEQgEgEAAgHIAAhxIgoCAIgjAAQgGAAgEgEQgEgEAAgHIAAiuIAbAAQANAAAAAPIAABxIAjhxQACgGAFgEQAFgFAIAAIAiAAIAAC9gAgNiYIAAi9IBFAAQATAAAKAJQAHAHACAPQABASgBAIQgDAUgPAHQAUAFACAbQAAAdgBAJQgHAjgpAAgAAai0IALAAQAIAAAEgEQAEgDACgJQACgNgCgQQgCgOgOAAIgNAAgAAakLIALAAQAPAAACgRQABgGgBgJQgBgNgOAAIgNAAgAj+iYQgOAAAAgPIAAiuIBKAAQAiAAAFAfQACASgCAWQgCAPgHALQgHAJgJADIgJADQgTACgTAAIAABLgAjjj8IAPAAQAOAAABgVQACgNgBgJQgBgRgQAAIgOAAgAnWiYQgNAAAAgPIAAhxIgpCAIgjAAQgNAAAAgPIAAiuIAbAAQANAAAAAPIAABxIAjhxQAEgPAQAAIAiAAIAAC9gAEol8IAAgHIAHAAQAPAAAAAJQAAAGAHAAQAIAAAAgGQAAgJAPAAIAHAAIAAAHQAAAXgeAAQgdAAAAgXg");

	this.addChild(this.shape);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(-71,-38.8,142.1,77.8);


(lib.t5 = function() {
	this.initialize();

	// <Слой>
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("ApvGFQgFAAgEgEQgEgEAAgHIAAgQIhVAAIAAAQQAAAHgDAEQgEAEgGAAIgUAAIAAg8IAMAAQAMgCgBgNIAAiRIBfAAQAGAAAEAEQADAFAAAGIAACRIAIAAQAFAAAEAFQAEADgBAIIAAAsgAq4E9IgBAMIAiAAIAAiDIghAAgAoOFqQgbgBgMgIQgPgJgCgZQgBgQgBglQAAgnACgQQAEgZAQgMQANgIAYgBQAcABANAMQALAJADAWQABAUAAAiQABAlgDATQgDAVgNALQgNAKgZABgAocDTQgBAOgBAoQAAAoABAMQADARAMAAQAMgBACgRIACg0QAAgogCgMQgBgSgMAAQgMAAgDARgAIOFmQgOAAAAgPIAAhVIgPAoIgQAtQgDAHgFADQgFAFgGAAIgfAAIAQgpIARgoQgTgJgEgcQgCgVACgTQAFgfAhAAIA9AAQANAAAAAOIAACvgAHiDYQgBAKABALQACAUAOAAIAOAAIAAg8IgNAAQgQAAgBATgAF9FmQgOAAAAgPIAAhIIgjAAIAABXIgcAAQgFAAgEgEQgEgEAAgHIAAiuIAcAAQANAAAAAPIAAA7IAjAAIAAhKIAcAAQAOAAAAAPIAACugADpFmQgNAAAAgPIAAhIIgjAAIAABXIgcAAQgNAAAAgPIAAiuIAcAAQANAAAAAPIAAA7IAjAAIAAhKIAbAAQAOAAAAAPIAACugABWFmQgNAAAAgPIAAiuIAcAAQANAAAAAPIAACugAAPFmQgNAAAAgPIAAiRIghAAIAACgIgcAAQgGAAgDgEQgFgEAAgHIAAiuIBmAAQANAAAAAPIAACugAiBFmQgGAAgDgEQgEgEgBgHIAAhyIgoCBIgjAAQgFAAgEgEQgEgEAAgHIAAiuIAbAAQANAAAAAOIAAByIAjhxQACgHAFgEQAFgEAHAAIAjAAIAAC9gAkaFmQgGAAgFgFQgEgEgCgGQgDgLgZhIIAABiIgcAAQgOAAAAgPIAAiuIAcAAQAOAAAAAPIAABLIAbhNQABgFAFgEQAEgEAHAAIAbAAIgiBWIAmBngAEsB3QgOAAAAgPIAAgQIhVAAIAAAQQAAAPgOAAIgUAAIAAg8IAMAAQANgCAAgNIAAiPIBdAAQAHAAADAEQAEAFAAAGIAACPIAHAAQANAAAAAQIAAAsgADiAuQAAAIgCAFIAiAAIAAiBIggAAgAkhB3QgNAAAAgPIAAgQIhWAAIAAAQQAAAPgNAAIgUAAIAAg8IAMAAQAMgCAAgNIAAiPIBeAAQAGAAAEAEQADAFAAAGIAACPIAIAAQANAAAAAQIAAAsgAlrAuIgBANIAiAAIAAiBIghAAgABXBbQgaAAgMgIQgPgJgCgZQgCgPAAgkQgBgnADgQQADgZAQgMQAOgIAYgBQAcABANAMQALAKACAVQACAUAAAiQAAAjgDATQgDAVgMALQgNAKgZAAgABKg5QgCAOAAAoQAAAmABAMQACARAMAAQANgBACgRIABgyQAAgogBgMQgBgSgNAAQgLAAgDARgAjBBbQgaAAgMgIQgPgJgCgZQgCgPgBgkQABgnACgQQADgZAQgMQANgIAZgBQAcABANAMQAKAJADAWQACAVgBAhQABAkgDASQgDAVgNALQgMAKgZAAgAjPg5QgBAOgBAoQAAAmABAMQAEARALAAQAMgBACgRIACgyQAAgogBgMIgDgMQgEgGgHAAQgMAAgDARgALYBYQgGAAgDgEQgEgEAAgHIAAhwIgoB/IgjAAQgOAAAAgPIAAisIAbAAQAOAAAAAOIAABwIAihvQACgHAFgEQAGgEAHAAIAiAAIAAC7gAI5BYQgOAAAAgPIAAg+IgZAAQgRAAgIgDQgKgEgHgHQgIgKAAgPIAAhHIAbAAQANAAAAAPIAAA1QABAUASAAIAQAAIAAhYIAcAAQAOAAAAAPIAACsgAGrBYQgNAAAAgPIAAhTIggBTQgBAHgFADQgGAFgGAAIgfAAIAhhRQgUgHgDgcQgDgSAEgWQAEgfAiAAIA8AAQANAAAAAOIAACtgAGAg0IAAAVQACAUAPAAIANAAIAAg8IgNAAQgQAAgBATgAhqBYIgBi7IBHAAQAUAAAKAJQAGAHABAPQACAQgCAKQgBAUgPAHQASAGACAYQAAAcgBAKQgFAjgpAAgAhBA7IALAAQAIAAAFgDQAEgEABgIQACgNgCgQQgCgOgOAAIgNAAgAhBgZIAKAAQAQAAACgRQABgGgBgKQgCgNgOABIgMAAgApYBYIAAi7IBbAAIAAAGQAAAJgGAGQgFAIgKAAIgdAAIAAAtIApAAIAAAFQgBAJgFAHQgFAFgKAAIgUAAIAAA5IAzAAIAAAHQgBAJgFAHQgGAHgKAAgAqSBYQgNAAAAgPIAAhIIgjAAIAABXIgcAAQgOAAAAgPIAAisIAcAAQAOAAAAAPIAAA7IAjAAIAAhKIAcAAQAFAAAEAEQAEAEAAAHIAACsgADEiUQgPABAAgOIADgkIAEgbIAUAAQAQAAAAALIgDAQIgQAxgAB9i0QgGAAgEgEQgDgEAAgHIAAhyIgpCBIgiAAQgHAAgDgEQgEgEAAgHIAAiuIAaAAQAOAAAAAOIAAByIAjhxQABgHAGgEQAFgEAIAAIAhAAIAAC9gAhDi0QgOAAAAgPIAAiNIgVAAQgJAAgGgGQgFgHAAgJIAAgLIB6AAIAAALQAAAJgDAHQgGAGgJAAIgVAAIAACcgAiti0QgNAAAAgPIAAiuIAbAAQANAAAAAPIAACugAk3i0QgOAAAAgPIAAiuIBKAAQAiAAAFAeQACASgCAXQgCAPgHAKQgIAJgIAEIgJADQgTACgTAAIAABLgAkckZIAOAAQAOABACgWQACgMgCgJQgBgRgQAAIgNAAgAmqi0QgGAAgDgEQgEgEgBgHIABiuIBbAAIAAAGQgBAJgFAGQgGAIgJAAIgdAAIgBCggAnni0QgHAAgFgFQgGgEgBgGIgJgsIgfAAIgJAsQgEAPgQAAIgVAAIAmi9IAiAAQANAAAGAEQAGAFADANIAiCngAoHkMIgKg8IgLA8IAVAAgAqJi0QgOAAAAgQIAAhQIgoAAIAABgIgeAAQgPAAAAgQIAAjAIAfAAQAGAAAFAEQADAFAAAIIAAA/IAoAAIAAhQIAeAAQAHAAADAEQAEAFABAIIAAC/g");
	this.shape.setTransform(0,1.4);

	this.addChild(this.shape);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(-75.5,-37.6,151.1,77.9);


(lib.t4 = function() {
	this.initialize();

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AJEBeQgGAAgDgEQgEgEAAgHIAAhwIgoB/IgjAAQgOAAAAgPIAAisIAbAAQANAAAAAOIAABwIAjhvQACgHAFgEQAFgEAIAAIAiAAIAAC7gAGCBeQgNAAAAgPIgBiLIgVAAQgJAAgFgHQgGgGAAgJIAAgLIB8AAIAAALQAAAJgFAGQgGAHgIAAIgWAAIAACagAEfBeQgOAAgDgPQgDgMgZhFIAABgIgcAAQgOAAAAgPIAAisIAcAAQAOAAAAAPIAABLIAbhMQABgGAEgEQAFgEAGAAIAcAAIgiBWIAmBlgABeBeQgGAAgEgEQgEgEAAgHIAAgOQALACAFgGQAFgFgDgKIgmiLIAbAAQAJAAAEAEQAFAEACAIIAPBXIAPhXQAEgQAQAAIAWAAIgoCMQgHAYgGAJQgKAOgQAAgAgxBeQgGAAgEgEQgEgEAAgHIAAisIBJAAQAhAAAFAfQADAVgDATQgBAPgIAIQgHAJgJAEIgJADQgQACgUAAIAABLgAgVgFIAOAAQAMABACgVQABgPgBgHQgBgRgOAAIgNAAgAiyBeQgNAAAAgPIAAgPQggAAgMgFQgPgGgDgTQgCgNAAgXQAAgbACgMQADgTAPgFQAMgGAgAAIAAgWIAbAAQAOAAAAAOIAAAIQAfAAANAGQAOAFADATQACAPAAAYQAAAUgCAQQgDATgOAGQgNAFgfAAIAAAegAiWAmQAKAAAEgCQAGgCABgJQACgHAAgUQAAgXgCgIQgBgIgGgDQgEgBgKAAgAjOgsQgGADgBAIIgCAfIACAbQABAJAGACQAEACALAAIAAhTQgLAAgEABgAlvBeQgQAAgEgPIgJgrIgfAAIgJArQgEAPgQAAIgVAAIAni7IAiAAQAMAAAGAEQAGAFAEANIAiClgAmQAGIgKg6IgLA6IAVAAgAonBeQgGAAgEgEQgEgEAAgHIAAiLIgWAAQgIAAgGgHQgFgGAAgJIAAgLIB8AAIAAALQAAAJgFAGQgGAHgJAAIgWAAIAACag");

	this.addChild(this.shape);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(-60.7,-9.4,121.5,18.9);


(lib.t3 = function() {
	this.initialize();

	// <Слой>
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("ABDD+QgOAAAAgPIAAgQIhaAAQgFAAgEgFQgEgEAAgHIAAitIAcAAQANAAAAAOIAACSIAhAAIAAigIAcAAQANAAAAAOIAACSIAHAAQAGAAAEAFQAEADAAAIIAAAsgAm6DOQgIgRAAg/QAAgyAIgSQALgbAmgBQAyAAACAnIAAAjIgOACQgaAAAAgVQAAgPgBgFQgDgGgIAAQgKAAgCARQgDARAAAkQAAAqACAKQACARALAAQAHAAADgIQADgHAAgVQAAgVAaABIANABIAAAsQgCAogwgBQgoAAgLgUgADCDfQgOAAAAgPIAAiuIAcAAQAOAAAAAPIAACugAB7DfQgOAAAAgPIAAiuIAcAAQANAAAAAPIAACugAilDfIAAi9IBbAAIAAAGQAAAJgFAGQgGAIgJAAIgdAAIAAAtIAoAAIAAAFQAAAJgFAHQgGAHgKAAIgTAAIAAA5IAyAAIAAAHQAAAJgFAHQgGAHgKAAgAjeDfQgGAAgEgEQgEgEAAgHIAAiRIgiAAIAACgIgcAAQgNAAAAgPIAAiuIBnAAQANAAAAAPIAACugADTAPQgGgFAAgIQAAgGAGgEQAFgGAIAAQAHAAAGAGQAFAEAAAGQAAAIgFAFQgGAFgHAAQgIAAgFgFgACmAPQgFgFAAgIQAAgGAFgEQAFgGAIAAQAHAAAGAGQAFAEAAAGQAAAIgFAFQgGAFgHAAQgIAAgFgFgAk1gLQgPAAAAgQIAAgSIheAAIAAASQAAAHgEAFQgEAEgHAAIgWAAIAAhCIANAAQANgDAAgOIAAifIBpAAQAGAAAEAEQAEAFAAAIIAACfIAIAAQAHAAAEAFQAEAEAAAJIAAAwgAmHhaQAAAHgBAGIAlAAIAAiRIgkAAgAADgOQgEAAgEgEQgEgEAAgHIAAgQIhUAAIAAAQQAAAHgEAEQgEAEgGAAIgUAAIAAg8IAMAAQAMgCAAgNIAAiRIBeAAQALAAAAAPIAACRIAIAAQANAAAAAQIAAAsgAhFhXIgBANIAiAAIAAiDIghAAgAjPgqQgaAAgNgIQgOgJgDgZQgBgQgBglQAAgoACgPQAEgZAQgMQAOgIAYgBQAcABAMAMQALAJADAWQACAUAAAiQAAAlgDATQgDAVgMALQgNAKgZAAgAjdjAQgBAOAAAoQgBAoACAMQACARAMAAQANgBACgRIABg0QAAgogBgMQgCgSgMAAQgMAAgDARgAGugtQgOAAAAgPIAAhyIgoCBIgjAAQgGAAgEgEQgEgEAAgHIAAiuIAbAAQANAAAAAOIAAByIAkhxQABgHAFgEQAFgEAIAAIAiAAIAAC9gADrgtQgGAAgDgEQgEgEAAgHIAAiNIgWAAQgJAAgFgGQgFgHAAgJIAAgLIB7AAIAAALQAAAJgFAHQgGAGgIAAIgWAAIAACcgACUgtQgHAAgGgFQgFgEgBgGIgJgsIgfAAIgKAsQgDAPgQAAIgVAAIAmi9IAiAAQANAAAGAEQAGAFADANIAiCngABziFIgJg8IgLA8IAUAAg");
	this.shape.setTransform(6.6,1.5);

	this.addChild(this.shape);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(-39,-24,91.3,50.9);


(lib.t2 = function() {
	this.initialize();

	// <Слой>
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("ABkGFQgOAAAAgPIAAgQIhVAAIAAAQQAAAPgLAAIgUAAIAAg8IALAAQANgCAAgNIAAiRIBcAAQAGAAAEAEQADAFAAAGIAACRIAHAAQAOAAAAAQIAAAsgAAaE9IgBAMIAhAAIAAiDIggAAgAkWFVQgJgRAAg/QAAgyAIgSQALgbAmgBQAyAAACAnIAAAjIgOACQgaAAAAgVQAAgPgBgFQgDgGgIAAQgKAAgCARQgDARAAAkQAAAqACALQACAQALAAQAHAAADgIQADgHAAgVQAAgVAaABIANABIAAAsQgBAogxAAQgogBgKgUgAlyFqQgagBgNgIQgOgJgDgZQgBgQgBglQAAgnACgQQAEgZAQgMQAOgIAYgBQAcABAMAMQALAJADAWQACAWAAAgQAAAmgDASQgDAVgNALQgMAKgZABgAmADTQgCAOAAAoQAAAoACAMQACARAMAAQANgBABgRIACg0QAAgogBgMIgDgMQgDgGgIAAQgNAAgCARgAh+FmQgGAAgEgEQgEgEAAgHIAAgOQALACAFgGQAFgFgDgKIgniNIAbAAQAJAAAFADQAFAEACAJIAPBZIAPhZQAEgQAQAAIAWAAIgoCOQgHAYgGAJQgKAOgRAAgAnkFmQgGAAgEgEQgEgEAAgHIAAiRIgiAAIAACgIgcAAQgNAAAAgPIAAiuIBnAAQAGAAAEAEQAEAFAAAGIAACugArvFmQgGAAgEgEQgEgEAAgHIAAgOQALACAFgGQAFgFgCgKIgniNIAbAAQAJAAAEADQAFAEACAJIAQBZIAOhZQAFgQAPAAIAXAAIgoCOQgHAYgHAJQgJAOgRAAgAg0AtIAAgYIAPgBQALABAGADQAIAEAAAMQAAAXAMAAQAIgBADgEQAEgGAAgNQAAgKgDgFQgDgFgHgEQgWgOgQgNQgPgNAAgZQAAg0A0gBQAzAAAAApIABAXIgLABQgcAAAAgRQAAgLgDgFQgEgEgHAAQgMAAAAARQAAALADAFQADAFAGAEQASAMARAOQALAHAEAIQAFALAAAQQAAAfgNANQgNAMgdAAQg0ABAAgvgApBBbQgaAAgNgIQgOgJgDgZQgBgQgBgjQAAgoACgPQAEgZAQgMQANgIAYgBQAcABANAMQALAJADAWQABAVAAAhQAAAkgCASQgDAVgNALQgMAKgZAAgApPg5QgCAOAAAoQAAAmACAMQACARAMAAQANgBABgRIACgyQAAgogBgMIgDgMQgDgGgIAAQgNAAgCARgAsKApIAAgZIAPgCQAcABAAAVQAAAZAQAAQAIgBAEgFQAEgFAAgOQAAgMgDgFQgDgGgIgEQgVgLgXgTQgQgOAAgcQAAg6A7AAQA2AAACAsIAAAaIgQAAQgcABAAgWQAAgMgDgDQgDgEgHAAQgPAAAAAWQAAAQAMAJIApAcQALAJAEAHQAGAKAAASQAAAjgMANQgOAPgkAAQg4AAAAgygAEEBYQgOAAAAgPIAAg5IgnhzIAcAAQAJAAAEADQAFAFACAIIAPBBIAPhBQAEgQAQAAIAXAAIgoB0IAABHgABSBYIgBi7IBHAAQAUAAAJAJQAIAHACAPQABAOgBAMQgDAUgPAHQAVAGABAYQABAXgDAPQgGAjgpAAgAB7A7IALAAQAPAAACgPQADgNgCgQQgBgOgPAAIgNAAgAB7gZIAKAAQAQAAACgRQABgGgBgKQgCgNgOABIgMAAgAhfBYQgPAAgEgPIgghSIAABhIgcAAQgNAAAAgPIAAisIBKAAQAiAAAEAfQACAVgBATQgEAcgUAHIAiBRgAiSgLIAOAAQAOAAACgUQABgLgBgKQgBgTgQABIgNAAgAkuBYIAAi7IBbAAIAAAGQAAAJgFAGQgGAIgKAAIgdAAIAAAtIApAAIAAAFQAAAJgGAHQgGAFgJAAIgUAAIAAA5IAyAAIAAAHQAAAJgFAHQgGAHgJAAgAloBYQgMAAAAgPIAAhfIgcBuIgLAAQgRAAgGgWIgXhYIAABuIgUAAQgNAAAAgPIAAisIAfAAQAMAAAGAEQAGAFAEANIAVBSIAWhTQAGgVAVAAIAdAAIAAC7gAJ1iVQgNAAAAgPIAAgQIhVAAIAAAQQAAAPgOAAIgUAAIAAg8IAMAAQAMgCAAgNIAAiRIBeAAQAGAAAEAEQAEAFAAAGIAACRIAHAAQANAAAAAQIAAAsgAIrjeIgBANIAiAAIAAiDIghAAgADXjFQgIgRAAg/QAAgyAIgSQALgbAmgBQAzAAAAAnIABAjIgOACQgaAAAAgVQAAgPgBgFQgDgGgIAAQgLAAgCARQgCARAAAkQAAAqACAKQABAKADADQADAEAFAAQAIAAADgIQACgHAAgVQAAgVAaABIAOABIAAAsQgCAogxgBQgnAAgLgUgAnNi0QgNgCAAgNIAAgOQATADAAgSIAAiRIBeAAQAGAAAEAEQADAFAAAGIAACuIgbAAQgOAAAAgPIAAiRIggAAIAAB2QAAAqgiAAIgGAAgAKui0QgNAAAAgPIAAiuIBKAAQAiAAAEAeQADASgCAXQgCAPgIAKQgHAJgIAEIgKADQgSACgTAAIAABLgALKkZIAOAAQAOABACgWQABgJgBgMQgBgRgQAAIgNAAgAG/i0QgGAAgDgEQgEgEAAgHIAAhyIgoCBIgjAAQgOAAAAgPIAAiuIAbAAQANAAAAAOIAAByIAjhxQACgHAFgEQAFgEAIAAIAiAAIAAC9gABRi0QgGAAgEgEQgEgEAAgHIAAhyIgoCBIghAAQgGAAgDgEQgEgEAAgHIAAiuIAYAAQAOAAAAAOIAAByIAjhxQABgHAGgEQAFgEAHAAIAiAAIAAC9gAhvi0QgGAAgEgEQgEgEAAgHIAAiNIgWAAQgIAAgGgGQgFgHAAgJIAAgLIB7AAIAAALQAAAJgFAHQgFAGgJAAIgWAAIAACcgAjYi0QgNAAAAgPIAAhyIgpCBIgjAAQgNAAAAgPIAAiuIAaAAQAOAAAAAOIAAByIAjhxQABgHAGgEQAFgEAIAAIAiAAIAAC9gAoDi0QgHAAgGgFQgFgEgBgGIgJgsIgfAAIgKAsQgDAPgQAAIgVAAIAmi9IAiAAQANAAAGAEQAGAFADANIAiCngAokkMIgJg8IgLA8IAUAAgAqli0QgPAAAAgQIAAhQIgnAAIAABgIgeAAQgPAAAAgQIAAjAIAfAAQAGAAAEAEQAEAFAAAIIAAA/IAnAAIAAhQIAfAAQAGAAAEAEQAEAFAAAIIAAC/g");
	this.shape.setTransform(4,0);

	this.addChild(this.shape);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(-74.7,-38.9,157.4,77.9);


(lib.s5_1 = function() {
	this.initialize();

	// Слой 1
	this.instance = new lib.s5();
	this.instance.setTransform(-10,-14);

	this.addChild(this.instance);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(-10,-14,20,28);


(lib.s4_1 = function() {
	this.initialize();

	// Слой 1
	this.instance = new lib.s4();
	this.instance.setTransform(-8.5,-11);

	this.addChild(this.instance);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(-8.5,-11,17,22);


(lib.s3_1 = function() {
	this.initialize();

	// Слой 1
	this.instance = new lib.s3();
	this.instance.setTransform(-14,-13);

	this.addChild(this.instance);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(-14,-13,28,26);


(lib.s2_1 = function() {
	this.initialize();

	// Слой 1
	this.instance = new lib.s2();
	this.instance.setTransform(-19.5,-15.5);

	this.addChild(this.instance);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(-19.5,-15.5,39,31);


(lib.s1_1 = function() {
	this.initialize();

	// Слой 1
	this.instance = new lib.s1();
	this.instance.setTransform(-24,-24.5);

	this.addChild(this.instance);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(-24,-24.5,48,49);


(lib.orange_1 = function() {
	this.initialize();

	// Слой 1
	this.instance = new lib.orange();
	this.instance.setTransform(-28.5,-33);

	this.addChild(this.instance);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(-28.5,-33,57,66);


(lib.line_1 = function() {
	this.initialize();

	// Слой 1
	this.instance = new lib.line();
	this.instance.setTransform(-57,-6);

	this.addChild(this.instance);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(-57,-6,114,12);


(lib.img1Mask = function() {
	this.initialize();

	// Слой 2 (mask)
	var mask = new cjs.Shape();
	mask._off = true;
	mask.graphics.p("AAAEDQkBgKk1g4IAAnFIRtAAIAAHiQjYAnjuAAQg4AAg5gCg");
	mask.setTransform(-53.5,-20.1);

}).prototype = p = new cjs.Container();
p.nominalBounds = null;


(lib.img1_1 = function() {
	this.initialize();

	// Слой 1
	this.instance = new lib.img1();
	this.instance.setTransform(-120,-189.2,0.8,0.8);

	this.addChild(this.instance);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(-120,-189.2,240,378.4);


(lib.HW = function() {
	this.initialize();

	// logo
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#1D1D1B").s().p("EgKwAs6IAAiGIjxAAIAACGQAAAIgFAFQgDAEgGAAQgNAAAAgRIAAiqIAkAAQAqhMALj0IAHmhICZAAIAALhIAtAAIAACqQAAARgNAAQgNAAAAgRgEgNIAliQgKDbgnBTICaAAIAAq+IhjAAQgEFkgCAsgEADNAolQAAgoADhQQADhRAAgjQAAgjgDhQQgDhQAAgoQAAhNAbgqQAagqAuAAQAvAAAaAqQAaAqAABNQAAAogCBQQgDBQAAAjQAAAjADBRQACBQAAAoQAAChhjAAQhjAAAAihgAD5f4QgRAjAAAzQAAA2ADBKQACBLAAAgIgCBrIgDCBQAAA5ARAgQASAlAlAAQAlAAATglQAQggAAg5IgDiBIgChrQAAggADhLQAChKAAg2QAAgzgRgjQgTgpgkAAQgjAAgUApgEgIQAolQAAgoADhQQADhRAAgjQAAgjgDhQQgDhQAAgoQAAhNAagqQAagqAvAAQAuAAAaAqQAbAqAABNQAAAogDBQQgDBQAAAjQAAAjADBRQADBQAAAoQAAChhjAAQhjAAAAihgAnkf4QgRAjAAAzQAAA2ACBKQADBLAAAgIgCBrIgDCBQAAA5AQAgQATAlAlAAQAlAAASglQARggAAg5QAAg1gDhMIgChrQAAggADhLQAChKAAg2QAAgzgRgjQgUgpgjAAQgjAAgUApgEgT5AqdQgYghAAhGIAAg4QAAgIAEgGQAEgFAGAAQAGAAAEAFQAEAGgBAIIAAA6QAAAzAPAXQAPAYAjAAQAlAAAQggQAOgcAAg6IAAiJQAAh7g9gEIgYAAQgHAAgEgEQgEgFAAgIQAAgHAEgFQADgFAGAAIAZAAQA+gEAAhzIAAhJQAAg6gOgcQgQggglAAQgjAAgPAYQgPAXAAAzIAAA6QABAIgEAGQgEAGgGAAQgGAAgEgGQgEgGAAgIIAAg4QAAhGAYghQAWgfAuAAQBeAAAACWIAABIQAABqgrAiQArAlAABsIAACJQAACWheAAQguAAgWgfgEAUKAqxQgEgFAAgJIAAmEIhBAAIhRGIQgEAJgEAEQgDADgGAAQgNAAAAgRIADgRIBQl4QgogHgNgmQgJgdAAhKIAAhDQAAhPARghQAVgmA3AAIBaAAIAALzQAAAJgEAFQgEAGgGAAQgGAAgEgGgASQf0QgKAWAAA8IAABDQAAA/AIAUQAMAgApAAIBDAAIAAkoIg+AAQgqAAgOAggEAJQAq2IAAsHIBPAAQA0AAAbAnQAaAnAABJIAABDQAABAgTAjQgPAcgXAFQAWAGAQAeQAUAlAAA6IAAB6QAABXgeAsQgcAqg0AAgEAJsAqTIAuAAQAoAAAVgjQAWgkAAhCIAAiFQAAgrgWgeQgWgfgfAAIg2AAgEAJsAj8IA2AAQAbAAAUgUQAbgaAAg1IAAhTQAAgzgUggQgVghgkAAIgzAAgEgCKAqxQgEgFAAgJIAAr0IBXAAQA8AAATAsQANAfAABXIAAArQAABTgQAjQgVAsg3AAIg7AAIAAGFQAAAJgEAFQgEAGgGAAQgGAAgEgGgEgByAj8IA7AAQAtAAALgnQAIgWAAhCIAAgsQAAhEgHgUQgKglgvAAIg7AAgEAOyAgoQgEgFAAgIIAAh8QAAgJAEgEQAEgFAFAAQAGAAADAFQAEAEAAAJIAAB8QAAAIgEAFQgDAEgGAAQgFAAgEgEgAwkduIAAiGIjxAAIAACGQAAARgNAAQgNAAAAgRIAAiqIAkAAQAphMALj0IAHmhICZAAIAALhIAtAAIAACqQAAARgNAAQgNAAAAgRgAy8WWQgKDbgnBTICbAAIAAq9IhjAAQgFFrgCAkgARiZZQAAgnADhRQAChQAAgjQAAgjgChQQgDhRAAgoQAAhMAagrQAagqAvAAQAuAAAaAqQAbArAABMQAAAogDBRQgDBQAAAjQAAAjADBQQADBRAAAnQAACihjAAQhjAAAAiigASOQsQgRAjAAAzQAAA3ACBKIACBrIgCBrIgCCAQAAA5AQAhQATAlAlAAQAlAAASglQARghAAg5IgDiAIgChrQAAghAChKQADhKAAg3QAAgzgRgjQgUgogjAAQgkAAgTAogAKeZZQAAgnADhRQADhQAAgjQAAgjgDhQQgDhRAAgoQAAhMAbgrQAagqAuAAQAvAAAaAqQAaArAABMQAAAogCBRQgDBQAAAjQAAAjADBQQACBRAAAnQAACihjAAQhjAAAAiigALKQsQgRAjAAAzQAAA3ADBKQACBKAAAhIgCBrIgDCAQAAA5ARAhQASAlAlAAQAlAAATglQAQghAAg5QAAg0gChMIgChrQAAghAChKQAChKAAg3QAAgzgRgjQgTgogkAAQgjAAgUAogADcbuQgFgEgCgIIgZi6IiJAAIgYC6QgBAIgFAEQgFAEgGgBQgGgBgDgHQgBgGAAgIIBormQADgTAMAAQAMAAADATIBrLmQABAIgDAGQgEAHgFABIgDAAQgEAAgDgDgAC3YFIg2mIQgGgtgCgjIgBgaIgCAAIAAAaQgCAjgHAtIg1GIIB/AAgAv4bbQAAgIAEgFQAFgFAJAAQAQAAAMgOQAJgLAIgXQAOguAFhlQACgsACiRIAClhICaAAIAALtQAAAVgOAAQgOAAAAgVIAArJIhhAAIgDFBQgDCngCAZQgEBkgPA2QgJAhgTAUQgTAUgVAAQgWAAAAgVgAOybYIAAr1ICRAAQANAAAAASQAAAHgDAFQgDAGgHAAIh2AAIAALRQAAATgOAAQgNAAAAgTgAjybqIAAsHIBPAAQA0AAAbAnQAaAnAABKIAABDQAABAgTAjQgPAcgXAFQAWAGAQAeQAUAlAAA5IAAB6QAABXgeAsQgcAqg0AAgAjXbIIAvAAQAoAAAVgkQAWgjAAhDIAAiEQAAgrgWgfQgWgegfAAIg3AAgAjXUwIA2AAQAbAAAVgTQAbgbAAg0IAAhTQAAg0gUgfQgVghgkAAIg0AAgAohbmQgEgGAAgIIAAmEIhBAAIhRGHQgEAKgEAEQgDACgGAAQgNAAAAgRQAAgFAEgLIBPl4QgogIgNgmQgJgcAAhKIAAhDQAAhPARghQAVgnA3AAIBaAAIAAL0QAAAIgEAGQgEAFgGAAQgGAAgEgFgAqbQoQgJAXAAA8IAABDQAAA/AHATQAMAgApAAIBDAAIAAkoIg+AAQgqAAgOAggAEnbqIAAryQAAgIAEgGQAEgGAGAAQAGAAAEAGQAEAGAAAIIAALQIBxAAIAArQQAAgIAEgGQAEgGAGAAQAGAAAEAGQAEAGAAAIIAALQIBxAAIAArQQAAgIAEgGQAEgGAGAAQAGAAAEAGQAEAGAAAIIAALygAgpOwQgFgFAAgIIAAiGIjxAAIAACGQAAAIgEAFQgEAEgFAAQgGAAgDgEQgEgFAAgIIAAiqIAkAAQAphMALj0IAImhICZAAIAALhIAtAAIAACqQAAAIgEAFQgEAEgFAAQgGAAgDgEgAjGHLQgKDbgnBTICbAAIAAq9IhjAAQgFFygCAdgABSMQQAAgIAEgFQAFgGAJAAQAQAAAMgNQAJgLAIgXQAOguAFhlQACgoACiVQABhUABkOICaAAIAALtQAAAWgOAAQgOAAAAgWIAArIIhhAAQgCBqgBDXIgEC/QgFBlgPA2QgJAggTAUQgTAUgVAAQgWAAAAgUgAKAMQIAAnBQAAg7ADhXIADhRIgCAAIgHAsIgRBiIhkIWQgFATgLAAQgIAAgEgHQgEgGAAgKIAArgQAAgIAEgFQADgGAGAAQAMAAAAATIAAHBQAAA/gCBTIgDBRIAEAAQAGg+AOhIIBmocQAEgVALAAQAIAAAFAHQAEAGAAAKIAALgQAAAIgEAGQgDAFgGAAQgNAAAAgTgAs6MbQgEgFAAgIIAAriQAAgIAEgFQAEgGAGAAQAGAAAEAGQAEAFAAAIIAAE8IAiAAIBrlFQACgFAEgDQADgCADAAQAGAAAEAIQAEAIgFANIhqE9IAAAEICDGFQAEAJAAAHQAAASgNAAQgGAAgDgDQgEgDgEgKIh/mDIgiAAIAAGDQAAAIgEAFQgEAGgGAAQgGAAgEgGgAM+MfIAAsHIBPAAQA0AAAbAnQAaAnAABJIAABDQAABAgTAjQgPAcgXAFQAWAGAQAeQAUAlAAA6IAAB6QAABXgeAsQgcAqg0AAgANZL8IAvAAQAoAAAVgjQAWgjAAhDIAAiFQAAgrgWgeQgWgfgfAAIg3AAgANZFlIA2AAQAbAAAVgUQAbgaAAg1IAAhTQAAgzgUggQgVgggkAAIg0AAgAnYMaQgEgFAAgJIAArgQAAgIAEgFQAEgGAGAAQAGAAAEAGQAEAFAAAIIAALgQAAAJgEAFQgEAGgGAAQgGAAgEgGgASSMfIAAsHICRAAQAHAAADAFQADAFAAAHQAAAHgDAGQgDAGgHAAIh1AAIAAEpIBlAAQANAAAAARQAAARgNAAIhlAAIAAFzIB1AAQAHAAADAGQADAFAAAHQAAAIgDAFQgDAGgHAAgA0LMfIAArzQAAgIAEgFQAEgGAGAAQAGAAAEAGQAEAFAAAIIAALQIBxAAIAArQQAAgIAEgFQAEgGAGAAQAGAAAEAGQAEAFAAAIIAALQIBxAAIAArQQAAgIAEgFQAEgGAGAAQAGAAAEAGQADAFAAAIIAALzgAFik7QAAgoADhRQADhQAAgjQAAgjgDhQQgDhRAAgoQAAhMAagrQAagqAvAAQAuAAAaAqQAbArAABMQAAAogDBRQgDBQAAAjQAAAjADBQQADBRAAAoQAAChhjAAQhjAAAAihgAGOtpQgRAjAAAzQAAA3ACBKQADBKAAAhIgCBrIgDCBQAAA5AQAgQATAlAlAAQAlAAASglQARggAAg5QAAg1gDhMIgChrQAAghADhKQAChKAAg3QAAgzgRgjQgUgogjAAQgjAAgUAogAjrk7QAAgoADhRQADhQAAgjQAAgjgDhQQgDhRAAgoQAAhMAbgrQAagqAuAAQAvAAAaAqQAbArAABMQAAAogDBRQgDBQAAAjQAAAjADBQQADBRAAAoQAAChhkAAQhjAAAAihgAi/tpQgRAjAAAzQAAA3ADBKQACBKAAAhIgCBrIgDCBQAAA4ARAhQASAlAlAAQAlAAATglQAQggAAg5QAAg1gChMIgChrQAAghAChKQAChKAAg3QAAgzgRgjQgTgogkAAQgjAAgUAogAwwinQgEgEgCgIIgai6IiIAAIgZC6QgBAIgFAEQgFAFgFgCQgGgBgEgHQgDgGABgIIBqrmQADgTAMAAQAMAAACATIBsLmQABAIgEAGQgDAHgGABIgDAAQgEAAgDgDgAxUmQIg2mIQgGgtgCgjIgBgaIgCAAIgBAaQgCAjgGAtIg1GIIB/AAgARQlGQAAgoADhRQADhQAAgjIAAgQIhCAAIAAGFQAAAIgEAGQgEAFgGAAQgGAAgEgFQgEgGAAgIIAArgQAAgIAEgGQAEgFAGAAQAGAAAEAFQAEAGAAAIIAAE4IBBAAQgFh8AAg8QAAhNAagrQAbgqAuAAQAuAAAbAqQAaArAABNQAAAngDBRQgDBQAAAjQAAAjADBQQADBRAAAoQAAChhjAAQhjAAAAihgAR8tzQgRAjAAAzQAAA2ACBKQADBLAAAgIgCBrIgDCBQAAA5AQAgQATAlAlAAQAlAAATglQAQggAAg5IgDiBIgChrQAAggADhLQAChKAAg2QAAgzgRgjQgUgpgjAAQgkAAgTApgAJ7i6QAAgHAEgGQAGgFAIAAQAQAAAMgOQAJgLAIgXQAOguAFhlQACgsACiRIAClhICaAAIAALtQAAAVgOAAQgOAAAAgVIAArIIhhAAIgDFBQgDCmgCAZQgEBkgPA2QgKAhgSAUQgTAUgVAAQgWAAAAgVgAu6i6QAAgHAFgGQAFgFAIAAQARAAALgOQAKgLAHgXQAPgtAFhmQABgoACiVIADlhICaAAIAALtQAAAVgOAAQgOAAAAgVIAArIIhiAAIgDFBQgDCmgBAZQgFBkgPA2QgJAhgTAUQgTAUgVAAQgWAAAAgVgAo4iuQgEgGAAgIIAArhQAAgIAEgGQAEgFAGAAQAGAAAEAFQAEAGAAAIIAAE8IAiAAIBrlGQAEgJAIAAQAHAAADAHQAEAJgFANIhqE8IAAAFICDGFQAEAJAAAHQAAARgOAAQgFAAgDgCQgEgEgEgKIh/mDIgiAAIAAGDQAAAIgEAGQgEAGgGAAQgGAAgEgGgABti9IAAr1ICRAAQAGAAAEAGQADAFAAAHQAAAHgDAFQgEAGgGAAIh2AAIAALRQAAATgOAAQgNAAAAgTgAsc0HQAAgoADhQQADhRAAgjQAAgigDhRQgDhQAAgoQAAhNAbgqQAagqAuAAQAuAAAbAqQAaAqAABNQAAAogDBQQgDBRAAAiQAAAjADBRQADBQAAAoQAAChhjAAQhjAAAAihgArw80QgRAjAAAzQAAA2ADBLIACBqIgCBrIgDCBQAAA5ARAhQASAlAlAAQAlAAATglQAQghAAg5IgDiBIgChrQAAggADhKQAChLAAg2QAAgzgRgjQgUgpgjAAQgjAAgUApgAzvyVQgYgqAAhNQAAgoADhRQAChQAAgjQAAgjgChQQgDhRAAgoQAAhNAYgqQAYgqAuAAQBEAAASBPQAKAtgEB3QAAAIgEAGQgEAGgGAAQgFAAgEgFQgEgFAAgJQAGhogGgkQgMhFg1AAQhDAAAAB+QAAA3ACBKQADBLAAAgQAAAhgDBKQgCBKAAA3QAAB+BDAAQA1AAAMhFQAGgkgGhnQAAgKAEgFQAEgFAFAAQAGAAAEAGQAEAGAAAJQAEB3gKAsQgSBPhEAAQguAAgYgqgAIixyQgFgEgCgJIgZi6IiJAAIgYC6QgCAJgEAEQgFAEgGgCQgGAAgDgHQgDgGABgIIBprnQADgSAMAAQAMAAADASIBrLnQABAIgDAGQgEAHgFAAIgEABQgDAAgDgDgAH91bIg2mJQgGgsgCgjIgBgaIgCAAIAAAaQgCAjgHAsIg1GJIB/AAgAgMyFIAAnBQAAg6ADhXIADhSIgCAAIh8KkQgFATgLAAQgIAAgEgHQgEgGAAgJIAArgQAAgJAEgFQADgGAGAAQANAAAAAUIAAHAQAAA/gDBTIgDBRIAEAAQAGg+AOhIIBmocQAFgVAKAAQAGAAAFAHQAEAGAAAKIAALgQAAAIgEAGQgDAFgFAAQgMAAAAgTgAmGx6QgEgFAAgIIAAmDIgfAAIhaGDQgEAKgEADQgDADgFAAQgOAAAAgRQAAgIAEgJIBdl+IhclIQgEgMAEgJQADgIAIAAQAHAAAEAKIBcFFIAgAAIAAk7QAAgJAEgFQAEgGAGAAQAGAAAEAGQAEAFAAAJIAAE7IAgAAIBalFQAEgKAHAAQAJAAADAIQAEAJgFAMIhbFIIBdF+QADAIAAAJQAAARgNAAQgLAAgGgQIhYmDIgfAAIAAGDQAAAIgEAFQgEAGgGAAQgGAAgEgGgAUFx7QgEgFAAgIIAAmEIhBAAIhRGHQgGAQgLAAQgNAAAAgRIADgQIBQl5QgogHgNgmQgJgdAAhKIAAhDQAAhOARghQAVgnA3AAIBaAAIAAL0QAAAIgEAFQgEAGgGAAQgGAAgEgGgASL84QgKAXAAA7IAABDQAAA/AIAUQAMAgApAAIBDAAIAAkoIg+AAQgqAAgOAggAQMx7QgEgFAAgIIAAmGIiDAAIAAGGQAAAIgEAFQgEAGgGAAQgGAAgEgGQgEgFAAgIIAArgQAAgJAEgFQAEgGAGAAQAGAAAEAGQAEAFAAAJIAAE4ICDAAIAAk4QAAgJAEgFQAEgGAGAAQAGAAAEAGQAEAFAAAJIAALgQAAAIgEAFQgEAGgGAAQgGAAgEgGgAMQx7QgEgFAAgIIAAmGIiDAAIAAGGQAAAIgEAFQgEAGgGAAQgGAAgEgGQgEgFAAgIIAArgQAAgJAEgFQAEgGAGAAQAGAAAEAGQAEAFAAAJIAAE4ICDAAIAAk4QAAgJAEgFQAEgGAGAAQAGAAAEAGQAEAFAAAJIAALgQAAAIgEAFQgEAGgGAAQgGAAgEgGgABWx2IAAsHIBPAAQA0AAAbAnQAaAnAABJIAABDQAABAgTAjQgPAcgXAFQAWAGAQAeQAUAlAAA6IAAB6QAABXgeAsQgcAqg0AAgABxyZIAvAAQAoAAAVgjQAWgjAAhDIAAiFQAAgrgWgeQgWgfgfAAIg3AAgABx4wIA2AAQAbAAAVgUQAbgaAAg0IAAhUQAAgzgUggQgVgggkAAIg0AAgAtxx7QgEgFAAgIIAArSIh5AAIAALSQAAAIgEAFQgEAGgGAAQgGAAgEgGQgEgFAAgIIAAr1ICxAAIAAL1QAAAIgEAFQgEAGgGAAQgGAAgEgGgAkf+wQgEgFAAgJIAAiGIjxAAIAACGQAAAJgEAFQgEAEgFAAQgGAAgDgEQgFgFAAgJIAAipIAlAAQAphMALj1IAHmgICZAAIAALhIAtAAIAACpQAAAJgEAFQgDAEgGAAQgFAAgEgEgEgG7gmVQgKDbgnBTICbAAIAAq+IhkAAQgEFkgCAsgEgLEgg+QgEgEgCgIIgai6IiIAAIgZC6QgBAIgFAEQgFAFgFgCQgGgBgEgHQgDgGABgIIBqrmQADgTAMAAQAMAAACATIBsLmQABAIgEAGQgDAHgGABIgDAAQgEAAgDgDgEgLogknIg2mIQgKhHABgjIgCAAQABAjgKBHIg1GIIB/AAgEABPghRIAAnAQAAhlAFiBIgBAAQgDAtgJA3Ig2FKQgCAMgGAIQgGAKgHAAQgHAAgGgIQgGgIgCgLIg2lNQgJg3gEgtIgBAAQAFB7AABrIAAHAQAAAUgMAAQgGAAgEgGQgDgFAAgJIAArgQAAgJAEgGQAEgHAIAAQAGAAAFAEQAFAEABAGQBAGxAMA+IACAAQAJg+BBmxQADgOAOAAQAPAAAAAWIAALgQAAAUgNAAQgMAAAAgUgEAPDghGQgEgGAAgIIAAmFIiDAAIAAGFQAAAIgEAGQgEAGgGAAQgGAAgDgGQgEgGAAgIIAArgQAAgIAEgGQADgFAGAAQAHAAADAFQAEAGAAAIIAAE4ICDAAIAAk4QAAgIAEgGQAEgFAGAAQAGAAAEAFQAEAGAAAIIAALgQAAAIgEAGQgEAGgGAAQgGAAgEgGgEAHYghGQgEgGAAgIIAAr0IBXAAQA9AAAUAsQANAfAABXIAAArQAABSgQAkQgVAsg5AAIg7AAIAAGFQAAAIgEAGQgEAGgGAAQgGAAgEgGgEAHwgn8IA7AAQAtAAANgmQAIgXAAhBIAAgsQAAhDgHgVQgNgmguAAIg7AAgEAEYghGQgEgGAAgIIAArgQAAgIAEgGQAEgFAGAAQAHAAADAFQAEAGAAAIIAALgQAAAIgEAGQgEAGgGAAQgGAAgEgGgEgRRghGQgEgGAAgIIAAmFIiDAAIAAGFQAAAIgEAGQgEAGgGAAQgGAAgEgGQgEgGAAgIIAArgQAAgIAEgGQAEgFAGAAQAGAAAEAFQAEAGAAAIIAAE4ICDAAIAAk4QAAgIAEgGQAEgFAGAAQAGAAAEAFQAEAGAAAIIAALgQAAAIgEAGQgEAGgGAAQgGAAgEgGgEAR/ghCIAAsGICRAAQAGAAAEAFQADAFAAAHQAAAHgDAFQgEAGgGAAIh1AAIAAEpIBlAAQAGAAAEAGQADAFAAAHQAAAHgDAFQgEAFgGAAIhlAAIAAFzIB1AAQAGAAAEAGQADAFAAAHQAAAHgDAFQgEAGgGAAg");
	this.shape.setTransform(0,0,0.865,0.813);

	// Слой 1
	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("EgSuAlgMAAAhK/MAldAAAMAAABK/g");

	this.addChild(this.shape_1,this.shape);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(-120,-240,240,480);


(lib.billet1_1 = function() {
	this.initialize();

	// Слой 1
	this.instance = new lib.billet1();
	this.instance.setTransform(-118,-151);

	this.addChild(this.instance);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(-118,-151,222,303);


(lib.bgImg_1 = function() {
	this.initialize();

	// Слой 1
	this.instance = new lib.bgImg();
	this.instance.setTransform(-120,-280,0.8,0.8);

	this.addChild(this.instance);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(-120,-280,240,480);


(lib.arrow3_1 = function() {
	this.initialize();

	// Слой 1
	this.instance = new lib.arrow3();
	this.instance.setTransform(-18.5,-41);

	this.addChild(this.instance);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(-18.5,-41,37,82);


(lib.arrow2_1 = function() {
	this.initialize();

	// Слой 1
	this.instance = new lib.arrow2();
	this.instance.setTransform(-13.5,-48);

	this.addChild(this.instance);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(-13.5,-48,27,96);


(lib.apple_1 = function() {
	this.initialize();

	// Слой 1
	this.instance = new lib.apple();
	this.instance.setTransform(-24,-38.5);

	this.addChild(this.instance);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(-24,-38.5,48,77);


(lib.Symbol = function() {
	this.initialize();

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#0A502F").s().p("AhTAXIAAgUQAAgIAHgJQAHgIAMgBICNABIAAAUQAAAIgHAJQgIAIgLABg");

	this.addChild(this.shape);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(-8.4,-2.4,16.9,4.8);


(lib._1 = function() {
	this.initialize();

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#C00000").s().p("AgaCXQgLgMAAgQQAAgQALgLQALgLAPAAQAPAAALALQALAMAAAPQAAAQgLAMQgLALgPgBQgPABgLgLgAgGBBQgKAAgHgHQgGgGAAgNIgGjIIAzABQAJAAAHAHQAGAGAAALIgKDJg");

	this.addChild(this.shape);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(-3.8,-16.2,7.8,32.4);


(lib.й1 = function() {
	this.initialize();

	// Слой 1
	this.instance = new lib.и1();
	this.instance.setTransform(0,3.2);

	this.shape = new cjs.Shape();
	this.shape.graphics.f("#C00000").s().p("AgogLIAAgIIALgBQATAAAAANQAAAEAEACQADABADAAQAKAAAAgHQAAgNAUAAIALABIAAAJQAAAfgpAAQgogBAAgfg");
	this.shape.setTransform(0.1,-14.1);

	this.addChild(this.shape,this.instance);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(-8.9,-16.2,17.8,32.5);


(lib.й = function() {
	this.initialize();

	// Слой 1
	this.instance = new lib.и();
	this.instance.setTransform(0,3.2);

	this.shape = new cjs.Shape();
	this.shape.graphics.f("#0A502F").s().p("AgogKIAAgJIAKgBQAVAAgBAOQAAAGAKAAQAEAAADgBQADgCABgDQAAgNATAAIALAAIAAAJQAAAfgpAAQgoAAAAgfg");
	this.shape.setTransform(0.1,-14.1);

	this.addChild(this.shape,this.instance);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(-8.9,-16.2,17.8,32.5);


(lib.vapor_1 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.instance = new lib.vaporMc();
	this.instance.setTransform(0,48.8,1,1,0,0,180);

	this.timeline.addTween(cjs.Tween.get(this.instance).to({y:0,alpha:0},25).wait(1).to({y:97.5},0).to({y:50.7,alpha:0.961},24).wait(1));

	// Слой 1
	this.instance_1 = new lib.vaporMc();
	this.instance_1.setTransform(0,97.5);
	this.instance_1.alpha = 0;

	this.timeline.addTween(cjs.Tween.get(this.instance_1).to({y:48.8,alpha:1},25).to({y:0,alpha:0},25).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-61.5,-100,123,297.5);


(lib.t1 = function() {
	this.initialize();

	// Слой 1
	this.instance = new lib._1();
	this.instance.setTransform(49.7,79.4);

	this.instance_1 = new lib.ш1();
	this.instance_1.setTransform(28,81.6);

	this.instance_2 = new lib.н1();
	this.instance_2.setTransform(4.2,81.5);

	this.instance_3 = new lib.у1();
	this.instance_3.setTransform(-14.1,81.5);

	this.instance_4 = new lib.п1();
	this.instance_4.setTransform(-32.5,81.5);

	this.instance_5 = new lib.й1();
	this.instance_5.setTransform(68.3,37.9);

	this.instance_6 = new lib.и1();
	this.instance_6.setTransform(47.4,41);

	this.instance_7 = new lib.в1();
	this.instance_7.setTransform(27.8,41);

	this.instance_8 = new lib.о1();
	this.instance_8.setTransform(9.3,41);

	this.instance_9 = new lib.р1();
	this.instance_9.setTransform(-8.1,40.9);

	this.instance_10 = new lib.д1();
	this.instance_10.setTransform(-28.7,43);

	this.instance_11 = new lib.и1();
	this.instance_11.setTransform(-50.4,40.9);

	this.instance_12 = new lib.с1();
	this.instance_12.setTransform(-69.8,40.9);

	this.instance_13 = new lib.й();
	this.instance_13.setTransform(53.7,1.9);

	this.instance_14 = new lib.и();
	this.instance_14.setTransform(32.8,5.1);

	this.instance_15 = new lib.ч();
	this.instance_15.setTransform(12.8,5);

	this.instance_16 = new lib.я();
	this.instance_16.setTransform(-6.2,5);

	this.instance_17 = new lib.р();
	this.instance_17.setTransform(-23.4,4.9);

	this.instance_18 = new lib.а();
	this.instance_18.setTransform(-42.7,4.9);

	this.instance_19 = new lib.г();
	this.instance_19.setTransform(-56.9,4.8);

	this.instance_20 = new lib.Symbol();
	this.instance_20.setTransform(50.5,-34.8);

	this.instance_21 = new lib.д();
	this.instance_21.setTransform(22.1,-33.4);

	this.instance_22 = new lib.н();
	this.instance_22.setTransform(1.3,-35.6);

	this.instance_23 = new lib.е();
	this.instance_23.setTransform(-15.4,-35.6);

	this.instance_24 = new lib.р();
	this.instance_24.setTransform(-31.9,-35.7);

	this.instance_25 = new lib.т();
	this.instance_25.setTransform(-50.4,-35.7);

	this.instance_26 = new lib.й();
	this.instance_26.setTransform(38.5,-79.3);

	this.instance_27 = new lib.и();
	this.instance_27.setTransform(17.6,-76.1);

	this.instance_28 = new lib.в();
	this.instance_28.setTransform(-1.9,-76.2);

	this.instance_29 = new lib.о();
	this.instance_29.setTransform(-20.5,-76.2);

	this.instance_30 = new lib.н();
	this.instance_30.setTransform(-39.4,-76.3);

	this.addChild(this.instance_30,this.instance_29,this.instance_28,this.instance_27,this.instance_26,this.instance_25,this.instance_24,this.instance_23,this.instance_22,this.instance_21,this.instance_20,this.instance_19,this.instance_18,this.instance_17,this.instance_16,this.instance_15,this.instance_14,this.instance_13,this.instance_12,this.instance_11,this.instance_10,this.instance_9,this.instance_8,this.instance_7,this.instance_6,this.instance_5,this.instance_4,this.instance_3,this.instance_2,this.instance_1,this.instance);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(-77.2,-95.5,154.4,191.1);


(lib.banner = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// HW
	this.instance = new lib.HW();
	this.instance.setTransform(0,-40);
	this.instance.alpha = 0;
	this.instance._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(359).to({_off:false},0).to({alpha:1},10).wait(65).to({alpha:0},5).wait(1));

	// t6
	this.instance_1 = new lib.t6();
	this.instance_1.setTransform(-209,-221.1);
	this.instance_1._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_1).wait(304).to({_off:false},0).to({x:-35.3},10,cjs.Ease.get(1)).to({_off:true},55).wait(71));

	// mask (mask)
	var mask = new cjs.Shape();
	mask._off = true;
	var mask_graphics_249 = new cjs.Graphics().p("AqYqVQgJgVACgYQAAgeAvgjQAtgiA6gPQA/gRAoAPQAvATAAA8QAAAphBAoQhGAqhVAAQg3AAgSgpg");
	var mask_graphics_250 = new cjs.Graphics().p("AjcBEQgOgWADgaQAAgfBJgmQBGgkBYgRQBigTA+ARQBIAUAABBQAAArhkArQhsAuiDAAQhVAAgcgtg");
	var mask_graphics_251 = new cjs.Graphics().p("AkqBKQgTgZAEgbQAAgiBjgpQBegnB4gSQCEgUBUASQBjAWAABGQAAAuiIAvQiSAxiyAAQh0AAglgwg");
	var mask_graphics_252 = new cjs.Graphics().p("Al5BPQgYgaAFgeQAAgkB9gsQB3gqCYgUQCngVBqATQB9AYAABLQAAAxisAzQi5A1jhAAQiRAAgwg0g");
	var mask_graphics_253 = new cjs.Graphics().p("AnIBUQgdgcAHggQAAgnCWguQCQgtC4gVQDKgXCAAVQCWAZAABQQAAA1jQA2QjfA5kPAAQixAAg5g4g");
	var mask_graphics_254 = new cjs.Graphics().p("AoWBaQgigeAIgiQAAgqCwgxQCpgwDXgWQDtgYCWAWQCwAaAABWQAAA4j0A5QkFA9k+AAQjPAAhDg7g");
	var mask_graphics_255 = new cjs.Graphics().p("AplBfQgnggAJgjQAAgsDKg1QDCgzD3gXQEPgaCsAXQDLAdAABaQAAA8kYA9QkrBAluAAQjtAAhNg/g");
	var mask_graphics_256 = new cjs.Graphics().p("Aq0psQgsghAKgmQAAgxDkg3QDbg2EXgZQEygbDCAZQDkAeAABfQAABCk7BAQlSBDmdAAQkLAAhXhCg");

	this.timeline.addTween(cjs.Tween.get(mask).to({graphics:null,x:0,y:0}).wait(249).to({graphics:mask_graphics_249,x:-67.3,y:-83.1}).wait(1).to({graphics:mask_graphics_250,x:-111,y:-156.5}).wait(1).to({graphics:mask_graphics_251,x:-102.5,y:-157.3}).wait(1).to({graphics:mask_graphics_252,x:-93.9,y:-158}).wait(1).to({graphics:mask_graphics_253,x:-85.3,y:-158.8}).wait(1).to({graphics:mask_graphics_254,x:-76.8,y:-159.6}).wait(1).to({graphics:mask_graphics_255,x:-68.2,y:-160.4}).wait(1).to({graphics:mask_graphics_256,x:-59.7,y:-88.9}).wait(1).to({graphics:null,x:0,y:0}).wait(183));

	// line
	this.instance_2 = new lib.line_1();
	this.instance_2.setTransform(-48.6,-166.1);
	this.instance_2._off = true;

	this.instance_2.mask = mask;

	this.timeline.addTween(cjs.Tween.get(this.instance_2).wait(249).to({_off:false},0).wait(45).to({x:-207.5},10,cjs.Ease.get(-1)).to({_off:true},1).wait(135));

	// t5
	this.instance_3 = new lib.t5();
	this.instance_3.setTransform(-204.4,-222.4);
	this.instance_3._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_3).wait(239).to({_off:false},0).to({x:-30.8},10,cjs.Ease.get(1)).wait(45).to({x:-204.4},10,cjs.Ease.get(-1)).to({_off:true},1).wait(135));

	// img1Mask
	this.instance_4 = new lib.img1Mask();
	this.instance_4.setTransform(0,11);
	this.instance_4.alpha = 0.141;
	this.instance_4._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_4).wait(239).to({_off:false},0).to({_off:true},130).wait(71));

	// mask (mask)
	var mask_1 = new cjs.Shape();
	mask_1._off = true;
	var mask_1_graphics_239 = new cjs.Graphics().p("AsDV7MgAegtUIYlAAMAAeAtUQmFBfmKAAQmHAAmPhfg");

	this.timeline.addTween(cjs.Tween.get(mask_1).to({graphics:null,x:0,y:0}).wait(239).to({graphics:mask_1_graphics_239,x:-45.2,y:-133.4}).wait(130).to({graphics:null,x:0,y:0}).wait(71));

	// vapor
	this.instance_5 = new lib.vapor_1();
	this.instance_5.setTransform(-56.7,-82.9);
	this.instance_5.alpha = 0;
	this.instance_5._off = true;

	this.instance_5.mask = mask_1;

	this.timeline.addTween(cjs.Tween.get(this.instance_5).wait(239).to({_off:false},0).to({alpha:1},10).to({_off:true},120).wait(71));

	// arrow3
	this.instance_6 = new lib.arrow3_1();
	this.instance_6.setTransform(2,-108.5,0.014,0.01,0,0,0,18.5,-40);
	this.instance_6._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_6).wait(184).to({_off:false},0).to({regX:16.5,regY:-39.5,scaleX:1.2,scaleY:1.2},10,cjs.Ease.get(1)).to({scaleX:1,scaleY:1},5).wait(30).to({regX:18.5,regY:-40,scaleX:0.01,scaleY:0.01},10,cjs.Ease.get(-1)).to({_off:true},1).wait(200));

	// t4
	this.instance_7 = new lib.t4();
	this.instance_7.setTransform(-219.2,-221);
	this.instance_7._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_7).wait(184).to({_off:false},0).to({x:-45.6},10,cjs.Ease.get(1)).wait(35).to({x:-219.2},10,cjs.Ease.get(-1)).to({_off:true},1).wait(200));

	// arrow2
	this.instance_8 = new lib.arrow2_1();
	this.instance_8.setTransform(-20.2,-143.8,0.019,0.01,0,0,0,-10.8,-50.1);
	this.instance_8._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_8).wait(129).to({_off:false},0).to({regX:-12,regY:-46.4,scaleX:1.29,scaleY:1.29,rotation:5.2},10,cjs.Ease.get(1)).to({scaleX:1,scaleY:1,rotation:0},5).wait(30).to({regX:-10.8,regY:-50.1,scaleX:0.02,scaleY:0.01},10,cjs.Ease.get(-1)).to({_off:true},1).wait(255));

	// t3
	this.instance_9 = new lib.t3();
	this.instance_9.setTransform(-240.9,-222.5);
	this.instance_9._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_9).wait(129).to({_off:false},0).to({x:-67.3},10,cjs.Ease.get(1)).wait(35).to({x:-240.9},10,cjs.Ease.get(-1)).to({_off:true},1).wait(255));

	// img1Mask
	this.instance_10 = new lib.img1Mask();
	this.instance_10.setTransform(0,11);
	this.instance_10.alpha = 0.5;
	this.instance_10._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_10).wait(129).to({_off:false},0).to({_off:true},111).wait(200));

	// mask (mask)
	var mask_2 = new cjs.Shape();
	mask_2._off = true;
	var mask_2_graphics_129 = new cjs.Graphics().p("AsLWvMgAOgu8IYlAAMAAOAu8QmFBfmKAAQmHAAmPhfg");

	this.timeline.addTween(cjs.Tween.get(mask_2).to({graphics:null,x:0,y:0}).wait(129).to({graphics:mask_2_graphics_129,x:-44.4,y:-138.6}).wait(111).to({graphics:null,x:0,y:0}).wait(200));

	// orange
	this.instance_11 = new lib.orange_1();
	this.instance_11.setTransform(-52.5,-314.9);
	this.instance_11._off = true;

	this.instance_11.mask = mask_2;

	this.timeline.addTween(cjs.Tween.get(this.instance_11).wait(194).to({_off:false},0).to({y:56.5},20).wait(5).to({y:-314.9},0).wait(1).to({y:-313},0).wait(1).to({y:-307},0).wait(1).to({y:-296.8},0).wait(1).to({y:-282.5},0).wait(1).to({y:-264},0).wait(1).to({y:-241.7},0).wait(1).to({y:-216},0).wait(1).to({y:-187.6},0).wait(1).to({y:-157.2},0).wait(1).to({y:-126},0).wait(1).to({y:-95},0).wait(1).to({y:-65.2},0).wait(1).to({y:-37.5},0).wait(1).to({y:-12.8},0).wait(1).to({y:8.5},0).wait(1).to({y:26},0).wait(1).to({y:39.5},0).wait(1).to({y:49},0).wait(1).to({y:54.7},0).wait(1).to({y:56.5},0).to({_off:true},1).wait(200));

	// apple
	this.instance_12 = new lib.apple_1();
	this.instance_12.setTransform(-52.5,-320.4);
	this.instance_12._off = true;

	this.instance_12.mask = mask_2;

	this.timeline.addTween(cjs.Tween.get(this.instance_12).wait(184).to({_off:false},0).wait(1).to({y:-318.5},0).wait(1).to({y:-312.4},0).wait(1).to({y:-302.1},0).wait(1).to({y:-287.5},0).wait(1).to({y:-268.8},0).wait(1).to({y:-246.2},0).wait(1).to({y:-220.1},0).wait(1).to({y:-191.2},0).wait(1).to({y:-160.4},0).wait(1).to({y:-128.7},0).wait(1).to({y:-97.2},0).wait(1).to({y:-67},0).wait(1).to({y:-38.9},0).wait(1).to({y:-13.8},0).wait(1).to({y:7.8},0).wait(1).to({y:25.5},0).wait(1).to({y:39.2},0).wait(1).to({y:48.9},0).wait(1).to({y:54.6},0).wait(1).to({y:56.5},0).wait(6).to({y:-320.4},0).wait(1).to({y:-318.5},0).wait(1).to({y:-312.4},0).wait(1).to({y:-302.1},0).wait(1).to({y:-287.5},0).wait(1).to({y:-268.8},0).wait(1).to({y:-246.2},0).wait(1).to({y:-220.1},0).wait(1).to({y:-191.2},0).wait(1).to({y:-160.4},0).wait(1).to({y:-128.7},0).wait(1).to({y:-97.2},0).wait(1).to({y:-67},0).wait(1).to({y:-38.9},0).wait(1).to({y:-13.8},0).wait(1).to({y:7.8},0).wait(1).to({y:25.5},0).wait(1).to({y:39.2},0).wait(1).to({y:48.9},0).wait(1).to({y:54.6},0).wait(1).to({y:56.5},0).to({_off:true},10).wait(200));

	// s
	this.instance_13 = new lib.s5_1();
	this.instance_13.setTransform(-48.5,-295.9);
	this.instance_13._off = true;

	this.instance_13.mask = mask_2;

	this.timeline.addTween(cjs.Tween.get(this.instance_13).wait(159).to({_off:false},0).to({y:41},20).to({_off:true},1).wait(260));

	// s
	this.instance_14 = new lib.s4_1();
	this.instance_14.setTransform(-48.5,-292.9);
	this.instance_14._off = true;

	this.instance_14.mask = mask_2;

	this.timeline.addTween(cjs.Tween.get(this.instance_14).wait(139).to({_off:false},0).to({y:41},20).to({_off:true},1).wait(280));

	// s
	this.instance_15 = new lib.s3_1();
	this.instance_15.setTransform(-48.5,-294.9);
	this.instance_15._off = true;

	this.instance_15.mask = mask_2;

	this.timeline.addTween(cjs.Tween.get(this.instance_15).wait(149).to({_off:false},0).to({y:41},20).to({_off:true},1).wait(270));

	// s
	this.instance_16 = new lib.s2_1();
	this.instance_16.setTransform(-48.5,-297.4);
	this.instance_16._off = true;

	this.instance_16.mask = mask_2;

	this.timeline.addTween(cjs.Tween.get(this.instance_16).wait(164).to({_off:false},0).to({y:41},20).to({_off:true},1).wait(255));

	// s
	this.instance_17 = new lib.s1_1();
	this.instance_17.setTransform(-48.5,-306.4);
	this.instance_17._off = true;

	this.instance_17.mask = mask_2;

	this.timeline.addTween(cjs.Tween.get(this.instance_17).wait(129).to({_off:false},0).to({y:41},20).to({_off:true},1).wait(290));

	// t2
	this.instance_18 = new lib.t2();
	this.instance_18.setTransform(-210,-216.9);
	this.instance_18._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_18).wait(74).to({_off:false},0).to({x:-31.6,y:-221},10,cjs.Ease.get(1)).wait(35).to({x:-205.3},10,cjs.Ease.get(-1)).to({_off:true},1).wait(310));

	// img1
	this.instance_19 = new lib.img1_1();
	this.instance_19.setTransform(-242,11);
	this.instance_19._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_19).wait(64).to({_off:false},0).to({x:0},10,cjs.Ease.get(-1)).to({_off:true},295).wait(71));

	// t1
	this.instance_20 = new lib.н();
	this.instance_20.setTransform(-39.4,-127);

	this.instance_21 = new lib.о();
	this.instance_21.setTransform(-20.5,-126.9);

	this.instance_22 = new lib.в();
	this.instance_22.setTransform(-1.9,-126.9);

	this.instance_23 = new lib.и();
	this.instance_23.setTransform(17.6,-126.8);

	this.instance_24 = new lib.й();
	this.instance_24.setTransform(38.5,-130);

	this.instance_25 = new lib.т();
	this.instance_25.setTransform(-50.4,-86.4);

	this.instance_26 = new lib.р();
	this.instance_26.setTransform(-31.9,-86.4);

	this.instance_27 = new lib.е();
	this.instance_27.setTransform(-15.4,-86.3);

	this.instance_28 = new lib.н();
	this.instance_28.setTransform(-39.4,-127);

	this.instance_29 = new lib.д();
	this.instance_29.setTransform(22.1,-84.1);

	this.instance_30 = new lib.Symbol();
	this.instance_30.setTransform(50.5,-85.5);

	this.instance_31 = new lib.г();
	this.instance_31.setTransform(-56.9,-45.9);

	this.instance_32 = new lib.а();
	this.instance_32.setTransform(-42.7,-45.8);

	this.instance_33 = new lib.р();
	this.instance_33.setTransform(-31.9,-86.4);

	this.instance_34 = new lib.я();
	this.instance_34.setTransform(-6.2,-45.7);

	this.instance_35 = new lib.ч();
	this.instance_35.setTransform(12.8,-45.7);

	this.instance_36 = new lib.и();
	this.instance_36.setTransform(17.6,-126.8);

	this.instance_37 = new lib.й();
	this.instance_37.setTransform(38.5,-130);

	this.instance_38 = new lib.с1();
	this.instance_38.setTransform(-69.8,-9.8);

	this.instance_39 = new lib.и1();
	this.instance_39.setTransform(-50.4,-9.8);

	this.instance_40 = new lib.д1();
	this.instance_40.setTransform(-28.7,-7.7);

	this.instance_41 = new lib.р1();
	this.instance_41.setTransform(-8.1,-9.8);

	this.instance_42 = new lib.о1();
	this.instance_42.setTransform(9.3,-9.7);

	this.instance_43 = new lib.в1();
	this.instance_43.setTransform(27.8,-9.7);

	this.instance_44 = new lib.и1();
	this.instance_44.setTransform(-50.4,-9.8);

	this.instance_45 = new lib.й1();
	this.instance_45.setTransform(68.3,-12.8);

	this.instance_46 = new lib.п1();
	this.instance_46.setTransform(-32.5,30.8);

	this.instance_47 = new lib.у1();
	this.instance_47.setTransform(-14.1,30.8);

	this.instance_48 = new lib.н1();
	this.instance_48.setTransform(4.2,30.8);

	this.instance_49 = new lib.ш1();
	this.instance_49.setTransform(28,30.9);

	this.instance_50 = new lib._1();
	this.instance_50.setTransform(49.7,28.7);

	this.instance_51 = new lib.t1();
	this.instance_51.setTransform(0,-50.7);
	this.instance_51._off = true;

	this.timeline.addTween(cjs.Tween.get({}).to({state:[]}).to({state:[{t:this.instance_20,p:{x:-39.4,y:-127}}]},11).to({state:[{t:this.instance_20,p:{x:-39.4,y:-127}},{t:this.instance_21}]},1).to({state:[{t:this.instance_20,p:{x:-39.4,y:-127}},{t:this.instance_21},{t:this.instance_22}]},1).to({state:[{t:this.instance_20,p:{x:-39.4,y:-127}},{t:this.instance_21},{t:this.instance_22},{t:this.instance_23,p:{x:17.6,y:-126.8}}]},1).to({state:[{t:this.instance_20,p:{x:-39.4,y:-127}},{t:this.instance_21},{t:this.instance_22},{t:this.instance_23,p:{x:17.6,y:-126.8}},{t:this.instance_24,p:{x:38.5,y:-130}}]},1).to({state:[{t:this.instance_20,p:{x:-39.4,y:-127}},{t:this.instance_21},{t:this.instance_22},{t:this.instance_23,p:{x:17.6,y:-126.8}},{t:this.instance_24,p:{x:38.5,y:-130}},{t:this.instance_25}]},1).to({state:[{t:this.instance_20,p:{x:-39.4,y:-127}},{t:this.instance_21},{t:this.instance_22},{t:this.instance_23,p:{x:17.6,y:-126.8}},{t:this.instance_24,p:{x:38.5,y:-130}},{t:this.instance_25},{t:this.instance_26,p:{x:-31.9,y:-86.4}}]},1).to({state:[{t:this.instance_20,p:{x:-39.4,y:-127}},{t:this.instance_21},{t:this.instance_22},{t:this.instance_23,p:{x:17.6,y:-126.8}},{t:this.instance_24,p:{x:38.5,y:-130}},{t:this.instance_25},{t:this.instance_26,p:{x:-31.9,y:-86.4}},{t:this.instance_27}]},1).to({state:[{t:this.instance_28},{t:this.instance_21},{t:this.instance_22},{t:this.instance_23,p:{x:17.6,y:-126.8}},{t:this.instance_24,p:{x:38.5,y:-130}},{t:this.instance_25},{t:this.instance_26,p:{x:-31.9,y:-86.4}},{t:this.instance_27},{t:this.instance_20,p:{x:1.3,y:-86.3}}]},1).to({state:[{t:this.instance_28},{t:this.instance_21},{t:this.instance_22},{t:this.instance_23,p:{x:17.6,y:-126.8}},{t:this.instance_24,p:{x:38.5,y:-130}},{t:this.instance_25},{t:this.instance_26,p:{x:-31.9,y:-86.4}},{t:this.instance_27},{t:this.instance_20,p:{x:1.3,y:-86.3}},{t:this.instance_29}]},1).to({state:[{t:this.instance_28},{t:this.instance_21},{t:this.instance_22},{t:this.instance_23,p:{x:17.6,y:-126.8}},{t:this.instance_24,p:{x:38.5,y:-130}},{t:this.instance_25},{t:this.instance_26,p:{x:-31.9,y:-86.4}},{t:this.instance_27},{t:this.instance_20,p:{x:1.3,y:-86.3}},{t:this.instance_29},{t:this.instance_30}]},1).to({state:[{t:this.instance_28},{t:this.instance_21},{t:this.instance_22},{t:this.instance_23,p:{x:17.6,y:-126.8}},{t:this.instance_24,p:{x:38.5,y:-130}},{t:this.instance_25},{t:this.instance_26,p:{x:-31.9,y:-86.4}},{t:this.instance_27},{t:this.instance_20,p:{x:1.3,y:-86.3}},{t:this.instance_29},{t:this.instance_30},{t:this.instance_31}]},1).to({state:[{t:this.instance_28},{t:this.instance_21},{t:this.instance_22},{t:this.instance_23,p:{x:17.6,y:-126.8}},{t:this.instance_24,p:{x:38.5,y:-130}},{t:this.instance_25},{t:this.instance_26,p:{x:-31.9,y:-86.4}},{t:this.instance_27},{t:this.instance_20,p:{x:1.3,y:-86.3}},{t:this.instance_29},{t:this.instance_30},{t:this.instance_31},{t:this.instance_32}]},1).to({state:[{t:this.instance_28},{t:this.instance_21},{t:this.instance_22},{t:this.instance_23,p:{x:17.6,y:-126.8}},{t:this.instance_24,p:{x:38.5,y:-130}},{t:this.instance_25},{t:this.instance_33},{t:this.instance_27},{t:this.instance_20,p:{x:1.3,y:-86.3}},{t:this.instance_29},{t:this.instance_30},{t:this.instance_31},{t:this.instance_32},{t:this.instance_26,p:{x:-23.4,y:-45.8}}]},1).to({state:[{t:this.instance_28},{t:this.instance_21},{t:this.instance_22},{t:this.instance_23,p:{x:17.6,y:-126.8}},{t:this.instance_24,p:{x:38.5,y:-130}},{t:this.instance_25},{t:this.instance_33},{t:this.instance_27},{t:this.instance_20,p:{x:1.3,y:-86.3}},{t:this.instance_29},{t:this.instance_30},{t:this.instance_31},{t:this.instance_32},{t:this.instance_26,p:{x:-23.4,y:-45.8}},{t:this.instance_34}]},1).to({state:[{t:this.instance_28},{t:this.instance_21},{t:this.instance_22},{t:this.instance_23,p:{x:17.6,y:-126.8}},{t:this.instance_24,p:{x:38.5,y:-130}},{t:this.instance_25},{t:this.instance_33},{t:this.instance_27},{t:this.instance_20,p:{x:1.3,y:-86.3}},{t:this.instance_29},{t:this.instance_30},{t:this.instance_31},{t:this.instance_32},{t:this.instance_26,p:{x:-23.4,y:-45.8}},{t:this.instance_34},{t:this.instance_35}]},1).to({state:[{t:this.instance_28},{t:this.instance_21},{t:this.instance_22},{t:this.instance_36},{t:this.instance_24,p:{x:38.5,y:-130}},{t:this.instance_25},{t:this.instance_33},{t:this.instance_27},{t:this.instance_20,p:{x:1.3,y:-86.3}},{t:this.instance_29},{t:this.instance_30},{t:this.instance_31},{t:this.instance_32},{t:this.instance_26,p:{x:-23.4,y:-45.8}},{t:this.instance_34},{t:this.instance_35},{t:this.instance_23,p:{x:32.8,y:-45.6}}]},1).to({state:[{t:this.instance_28},{t:this.instance_21},{t:this.instance_22},{t:this.instance_36},{t:this.instance_37},{t:this.instance_25},{t:this.instance_33},{t:this.instance_27},{t:this.instance_20,p:{x:1.3,y:-86.3}},{t:this.instance_29},{t:this.instance_30},{t:this.instance_31},{t:this.instance_32},{t:this.instance_26,p:{x:-23.4,y:-45.8}},{t:this.instance_34},{t:this.instance_35},{t:this.instance_23,p:{x:32.8,y:-45.6}},{t:this.instance_24,p:{x:53.7,y:-48.8}}]},1).to({state:[{t:this.instance_28},{t:this.instance_21},{t:this.instance_22},{t:this.instance_36},{t:this.instance_37},{t:this.instance_25},{t:this.instance_33},{t:this.instance_27},{t:this.instance_20,p:{x:1.3,y:-86.3}},{t:this.instance_29},{t:this.instance_30},{t:this.instance_31},{t:this.instance_32},{t:this.instance_26,p:{x:-23.4,y:-45.8}},{t:this.instance_34},{t:this.instance_35},{t:this.instance_23,p:{x:32.8,y:-45.6}},{t:this.instance_24,p:{x:53.7,y:-48.8}},{t:this.instance_38}]},1).to({state:[{t:this.instance_28},{t:this.instance_21},{t:this.instance_22},{t:this.instance_36},{t:this.instance_37},{t:this.instance_25},{t:this.instance_33},{t:this.instance_27},{t:this.instance_20,p:{x:1.3,y:-86.3}},{t:this.instance_29},{t:this.instance_30},{t:this.instance_31},{t:this.instance_32},{t:this.instance_26,p:{x:-23.4,y:-45.8}},{t:this.instance_34},{t:this.instance_35},{t:this.instance_23,p:{x:32.8,y:-45.6}},{t:this.instance_24,p:{x:53.7,y:-48.8}},{t:this.instance_38},{t:this.instance_39,p:{x:-50.4,y:-9.8}}]},1).to({state:[{t:this.instance_28},{t:this.instance_21},{t:this.instance_22},{t:this.instance_36},{t:this.instance_37},{t:this.instance_25},{t:this.instance_33},{t:this.instance_27},{t:this.instance_20,p:{x:1.3,y:-86.3}},{t:this.instance_29},{t:this.instance_30},{t:this.instance_31},{t:this.instance_32},{t:this.instance_26,p:{x:-23.4,y:-45.8}},{t:this.instance_34},{t:this.instance_35},{t:this.instance_23,p:{x:32.8,y:-45.6}},{t:this.instance_24,p:{x:53.7,y:-48.8}},{t:this.instance_38},{t:this.instance_39,p:{x:-50.4,y:-9.8}},{t:this.instance_40}]},1).to({state:[{t:this.instance_28},{t:this.instance_21},{t:this.instance_22},{t:this.instance_36},{t:this.instance_37},{t:this.instance_25},{t:this.instance_33},{t:this.instance_27},{t:this.instance_20,p:{x:1.3,y:-86.3}},{t:this.instance_29},{t:this.instance_30},{t:this.instance_31},{t:this.instance_32},{t:this.instance_26,p:{x:-23.4,y:-45.8}},{t:this.instance_34},{t:this.instance_35},{t:this.instance_23,p:{x:32.8,y:-45.6}},{t:this.instance_24,p:{x:53.7,y:-48.8}},{t:this.instance_38},{t:this.instance_39,p:{x:-50.4,y:-9.8}},{t:this.instance_40},{t:this.instance_41}]},1).to({state:[{t:this.instance_28},{t:this.instance_21},{t:this.instance_22},{t:this.instance_36},{t:this.instance_37},{t:this.instance_25},{t:this.instance_33},{t:this.instance_27},{t:this.instance_20,p:{x:1.3,y:-86.3}},{t:this.instance_29},{t:this.instance_30},{t:this.instance_31},{t:this.instance_32},{t:this.instance_26,p:{x:-23.4,y:-45.8}},{t:this.instance_34},{t:this.instance_35},{t:this.instance_23,p:{x:32.8,y:-45.6}},{t:this.instance_24,p:{x:53.7,y:-48.8}},{t:this.instance_38},{t:this.instance_39,p:{x:-50.4,y:-9.8}},{t:this.instance_40},{t:this.instance_41},{t:this.instance_42}]},1).to({state:[{t:this.instance_28},{t:this.instance_21},{t:this.instance_22},{t:this.instance_36},{t:this.instance_37},{t:this.instance_25},{t:this.instance_33},{t:this.instance_27},{t:this.instance_20,p:{x:1.3,y:-86.3}},{t:this.instance_29},{t:this.instance_30},{t:this.instance_31},{t:this.instance_32},{t:this.instance_26,p:{x:-23.4,y:-45.8}},{t:this.instance_34},{t:this.instance_35},{t:this.instance_23,p:{x:32.8,y:-45.6}},{t:this.instance_24,p:{x:53.7,y:-48.8}},{t:this.instance_38},{t:this.instance_39,p:{x:-50.4,y:-9.8}},{t:this.instance_40},{t:this.instance_41},{t:this.instance_42},{t:this.instance_43}]},1).to({state:[{t:this.instance_28},{t:this.instance_21},{t:this.instance_22},{t:this.instance_36},{t:this.instance_37},{t:this.instance_25},{t:this.instance_33},{t:this.instance_27},{t:this.instance_20,p:{x:1.3,y:-86.3}},{t:this.instance_29},{t:this.instance_30},{t:this.instance_31},{t:this.instance_32},{t:this.instance_26,p:{x:-23.4,y:-45.8}},{t:this.instance_34},{t:this.instance_35},{t:this.instance_23,p:{x:32.8,y:-45.6}},{t:this.instance_24,p:{x:53.7,y:-48.8}},{t:this.instance_38},{t:this.instance_44},{t:this.instance_40},{t:this.instance_41},{t:this.instance_42},{t:this.instance_43},{t:this.instance_39,p:{x:47.4,y:-9.7}}]},1).to({state:[{t:this.instance_28},{t:this.instance_21},{t:this.instance_22},{t:this.instance_36},{t:this.instance_37},{t:this.instance_25},{t:this.instance_33},{t:this.instance_27},{t:this.instance_20,p:{x:1.3,y:-86.3}},{t:this.instance_29},{t:this.instance_30},{t:this.instance_31},{t:this.instance_32},{t:this.instance_26,p:{x:-23.4,y:-45.8}},{t:this.instance_34},{t:this.instance_35},{t:this.instance_23,p:{x:32.8,y:-45.6}},{t:this.instance_24,p:{x:53.7,y:-48.8}},{t:this.instance_38},{t:this.instance_44},{t:this.instance_40},{t:this.instance_41},{t:this.instance_42},{t:this.instance_43},{t:this.instance_39,p:{x:47.4,y:-9.7}},{t:this.instance_45}]},1).to({state:[{t:this.instance_28},{t:this.instance_21},{t:this.instance_22},{t:this.instance_36},{t:this.instance_37},{t:this.instance_25},{t:this.instance_33},{t:this.instance_27},{t:this.instance_20,p:{x:1.3,y:-86.3}},{t:this.instance_29},{t:this.instance_30},{t:this.instance_31},{t:this.instance_32},{t:this.instance_26,p:{x:-23.4,y:-45.8}},{t:this.instance_34},{t:this.instance_35},{t:this.instance_23,p:{x:32.8,y:-45.6}},{t:this.instance_24,p:{x:53.7,y:-48.8}},{t:this.instance_38},{t:this.instance_44},{t:this.instance_40},{t:this.instance_41},{t:this.instance_42},{t:this.instance_43},{t:this.instance_39,p:{x:47.4,y:-9.7}},{t:this.instance_45},{t:this.instance_46}]},1).to({state:[{t:this.instance_28},{t:this.instance_21},{t:this.instance_22},{t:this.instance_36},{t:this.instance_37},{t:this.instance_25},{t:this.instance_33},{t:this.instance_27},{t:this.instance_20,p:{x:1.3,y:-86.3}},{t:this.instance_29},{t:this.instance_30},{t:this.instance_31},{t:this.instance_32},{t:this.instance_26,p:{x:-23.4,y:-45.8}},{t:this.instance_34},{t:this.instance_35},{t:this.instance_23,p:{x:32.8,y:-45.6}},{t:this.instance_24,p:{x:53.7,y:-48.8}},{t:this.instance_38},{t:this.instance_44},{t:this.instance_40},{t:this.instance_41},{t:this.instance_42},{t:this.instance_43},{t:this.instance_39,p:{x:47.4,y:-9.7}},{t:this.instance_45},{t:this.instance_46},{t:this.instance_47}]},1).to({state:[{t:this.instance_28},{t:this.instance_21},{t:this.instance_22},{t:this.instance_36},{t:this.instance_37},{t:this.instance_25},{t:this.instance_33},{t:this.instance_27},{t:this.instance_20,p:{x:1.3,y:-86.3}},{t:this.instance_29},{t:this.instance_30},{t:this.instance_31},{t:this.instance_32},{t:this.instance_26,p:{x:-23.4,y:-45.8}},{t:this.instance_34},{t:this.instance_35},{t:this.instance_23,p:{x:32.8,y:-45.6}},{t:this.instance_24,p:{x:53.7,y:-48.8}},{t:this.instance_38},{t:this.instance_44},{t:this.instance_40},{t:this.instance_41},{t:this.instance_42},{t:this.instance_43},{t:this.instance_39,p:{x:47.4,y:-9.7}},{t:this.instance_45},{t:this.instance_46},{t:this.instance_47},{t:this.instance_48}]},1).to({state:[{t:this.instance_28},{t:this.instance_21},{t:this.instance_22},{t:this.instance_36},{t:this.instance_37},{t:this.instance_25},{t:this.instance_33},{t:this.instance_27},{t:this.instance_20,p:{x:1.3,y:-86.3}},{t:this.instance_29},{t:this.instance_30},{t:this.instance_31},{t:this.instance_32},{t:this.instance_26,p:{x:-23.4,y:-45.8}},{t:this.instance_34},{t:this.instance_35},{t:this.instance_23,p:{x:32.8,y:-45.6}},{t:this.instance_24,p:{x:53.7,y:-48.8}},{t:this.instance_38},{t:this.instance_44},{t:this.instance_40},{t:this.instance_41},{t:this.instance_42},{t:this.instance_43},{t:this.instance_39,p:{x:47.4,y:-9.7}},{t:this.instance_45},{t:this.instance_46},{t:this.instance_47},{t:this.instance_48},{t:this.instance_49}]},1).to({state:[{t:this.instance_28},{t:this.instance_21},{t:this.instance_22},{t:this.instance_36},{t:this.instance_37},{t:this.instance_25},{t:this.instance_33},{t:this.instance_27},{t:this.instance_20,p:{x:1.3,y:-86.3}},{t:this.instance_29},{t:this.instance_30},{t:this.instance_31},{t:this.instance_32},{t:this.instance_26,p:{x:-23.4,y:-45.8}},{t:this.instance_34},{t:this.instance_35},{t:this.instance_23,p:{x:32.8,y:-45.6}},{t:this.instance_24,p:{x:53.7,y:-48.8}},{t:this.instance_38},{t:this.instance_44},{t:this.instance_40},{t:this.instance_41},{t:this.instance_42},{t:this.instance_43},{t:this.instance_39,p:{x:47.4,y:-9.7}},{t:this.instance_45},{t:this.instance_46},{t:this.instance_47},{t:this.instance_48},{t:this.instance_49},{t:this.instance_50}]},1).to({state:[{t:this.instance_51}]},23).to({state:[{t:this.instance_51}]},10).to({state:[]},1).wait(365));
	this.timeline.addTween(cjs.Tween.get(this.instance_51).wait(64).to({_off:false},0).to({x:227.5},10,cjs.Ease.get(-1)).to({_off:true},1).wait(365));

	// billet1
	this.instance_52 = new lib.billet1_1();
	this.instance_52.setTransform(-236,-40.2);

	this.timeline.addTween(cjs.Tween.get(this.instance_52).to({x:6.5},11,cjs.Ease.get(1)).wait(53).to({x:234},10,cjs.Ease.get(-1)).to({_off:true},1).wait(365));

	// bgImg
	this.instance_53 = new lib.bgImg_1();

	this.timeline.addTween(cjs.Tween.get(this.instance_53).wait(440));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-354,-280,474,480);


// stage content:
(lib._300x600 = function() {
	this.initialize();

	// cover
	this.shape = new cjs.Shape();
	this.shape.graphics.f().s("#666666").ss(2,1,1).p("EgXbgu3MAu3AAAMAAABdvMgu3AAAg");
	this.shape.setTransform(150,300);

	// banner
	this.instance = new lib.banner();
	this.instance.setTransform(150,350,1.25,1.25);

	this.addChild(this.instance,this.shape);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(-142.5,299,593.5,602);

})(lib = lib||{}, images = images||{}, createjs = createjs||{}, ss = ss||{});
var lib, images, createjs, ss;